### ISSUE TITLE
Working with on ADFSv2

### ISSUE THREAD

**Issue by dhatsch** [jobec/django-auth-adfs#10]
Hi,
In the doc you mention ADFSv3 as a prerequisite. Our customer is using ADFSv2, did you try on ADFSv2?
Kind regards
Didier

**Comment by jobec** [comment]
This won't work with ADFSv2 because it doesn't support OAuth tokens.

http://activedirectoryfaq.com/2015/01/new-features-in-adfs-3-0-active-directory-federation-services/#OAUTH2-Token-Support-in-ADFS-30

**Comment by dhatsch** [comment]
Hi thanks for your quick answer. We'll have to wait until an update on our customer side.
By the way thanks for coding the django-auth-adfs lib :)
Kind regards

**Comment by jobec** [comment]
No problem and it's nice to see someone is using my package :)
