### ISSUE TITLE
Azure AD with openid configuration

### ISSUE THREAD

**Issue by rvishna** [jobec/django-auth-adfs#100]
In the config.py, the function `_load_openid_config` forms the OpenID configuration URL by combining the SERVER and TENANT_ID settings, yet these two are not both allowed to be specified. How then should one use the OpenID configuration for key discovery?

I'm using Azure AD to get an access token and the oauth2 mode doesn't work, but openid connect does (maybe this is after a change made on Azure?)

**Comment by jobec** [comment]
Only ADFS on Server 2012 is full OAuth2. Starting with 2016 and up (or AzureAD) it's all OpenID Connect.

So, you point the config to a Server 2012 or 2016/2019 server by using the `SERVER` setting, or you point to AzureAD by using the `TENANT_ID` setting. Discovery of what mode to use then happens automatically.
