### ISSUE TITLE
Azure AD - Invalid Issuer 

### ISSUE THREAD

**Issue by apichate-sage** [jobec/django-auth-adfs#103]
I send a token which I get from Azure AD to Django Rest API on my local but I get "Invalid issuer". Could anyone give me some suggestions?

**This is what are printed on console,**

django_auth_adfs loaded settings from ADFS server.
operating mode:         openid_connect
authorization endpoint: https://login.microsoftonline.com/xxxx-yyyy-zzzz/oauth2/authorize
token endpoint:         https://login.microsoftonline.com/xxxx-yyyy-zzzz/oauth2/token
end session endpoint:   https://login.microsoftonline.com/xxxx-yyyy-zzzz/oauth2/logout
issuer:                 https://sts.windows.net/xxxx-yyyy-zzzz/

**This is parameter that I use for get token**

URL https://login.microsoftonline.com/xxxx-yyyy-zzzz/oauth2/token
grant_type - password
client_id - XXXX
username - YYYY
password - ZZZZ
resource - api://WWW-YYYY-ZZZZ

then I use 'access_token' in response to call Django Rest API on my local

URL - http://localhost:8000/api/items
Authorization JWT + access_token

**This is my configure in setting.py**

AUTH_ADFS = {
    "TENANT_ID": "ddddd-ddddd-ddddd",
    "CLIENT_ID": "ccccc-ccccc-ccccc",
    "RELYING_PARTY_ID": "api://bbbbb-bbbbb-bbbbb",
    "AUDIENCE": "api://aaaaa-aaaaaa-aaaaaa",
    "LOGIN_EXEMPT_URLS": ["^api", ],
    "CLAIM_MAPPING": {"first_name": "given_name",
                                      "last_name": "family_name", },
    "USERNAME_CLAIM": "email",
}

Invalid issuer
Unauthorized: /api/items/

**Comment by gunflap** [comment]
Did you ever figure this out? Having the same issue.

**Comment by marlonpatrick** [comment]
@apichate-sage did you managed to solve that problem?
