### ISSUE TITLE
Getting this module to work

### ISSUE THREAD

**Issue by patrikbi** [jobec/django-auth-adfs#11]
Getting different issues as I try to find my way.

I have followed the instructions best I can. 

Environment:
I'm running a lab environment with a Microsoft AD FS server and Domain Controller. 
Ubuntu server running my django app.

My AUTH_ADFS settings are as follows.
AUTH_ADFS = {
    "SERVER": "lab.local",
    "CLIENT_ID": "LogSearch",
    "RESOURCE": "logsearch",
    #"AUDIENCE": "microsoft:identityserver:https://lab.local/adfs/oauth2/token",
    #"SIGNING_CERT": "/webapps/logsearch/adfs.pem",
    "ISSUER": "https://lab.local/adfs/oauth2/token",
    "CA_BUNDLE": "/webapps/logsearch/adfs.pem",
    #"CA_BUNDLE": "False",
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
    "REDIR_URI": "https://lab.local/adfs/ls",
}

I have been flipping the settings around a lot. When I do I get different errors. With the current setup:

TypeError at /oauth2/login
'instancemethod' object has no attribute '__getitem__'

Request Method: GET 
Request URL: http://logsearch.lab.local/oauth2/login 

Django Version:
1.10.6 

Exception Value:
'instancemethod' object has no attribute '__getitem__'
 

Brg,
Patrik

**Comment by jobec** [comment]
Could you provide an entire trace back? That should make it clear where the error is coming from exactly.

**Comment by jobec** [comment]
Oh, and the output of ``pip freeze`` would also be interesting.

**Comment by patrikbi** [comment]
Hi,

Output from pip freeze:
(logsearch) logsearch@LogSearch:~$ pip freeze
appdirs==1.4.3
asn1crypto==0.22.0
cffi==1.9.1
cryptography==1.8.1
Django==1.10.6
django-auth-adfs==0.1.2
enum34==1.1.6
gunicorn==19.7.0
idna==2.5
ipaddress==1.0.18
packaging==16.8
pkg-resources==0.0.0
psycopg2==2.7.1
pycparser==2.17
PyJWT==1.4.2
pyparsing==2.2.0
requests==2.13.0
setproctitle==1.1.10
six==1.10.0


Trace back:
Request agianst ./manage.py runserver
MultiValueDictKeyError at /oauth2/login
"'code'"

/webapps/logsearch/local/lib/python2.7/site-packages/django_auth_adfs/views.py in get 
12.        """

13.        Handles the redirect from ADFS to our site.

14.        We try to process the passed authorization code and login the user.

15.

16.        Args:

17.            request (django.http.request.HttpRequest): A Django Request object

18.        """

19.        code = request.GET["code"]
 ...
20.

21.        user = authenticate(authorization_code=code)

22.

23.        if user is not None:

24.            if user.is_active:

25.                login(request, user)


Variable
Value
request <WSGIRequest: GET '/oauth2/login'>
self <django_auth_adfs.views.OAuth2View object at 0x7f339c4d5850>
 




Using Gunicorn
'instancemethod' object has no attribute '__getitem__'
 
/webapps/logsearch/local/lib/python2.7/site-packages/django_auth_adfs/views.py in get 
12.        """

13.        Handles the redirect from ADFS to our site.

14.        We try to process the passed authorization code and login the user.

15.

16.        Args:

17.            request (django.http.request.HttpRequest): A Django Request object

18.        """

19.        code = request.GET["code"]
 ...
20.

21.        user = authenticate(authorization_code=code)

22.

23.        if user is not None:

24.            if user.is_active:

25.                login(request, user)



Variable

Value


request <WSGIRequest: GET '/oauth2/login'>
 
self <django_auth_adfs.views.OAuth2View object at 0x7f339c4d5850>

**Comment by jobec** [comment]
That's a strange traceback...

You haven't gotten one like this example? (Completely unrelated and just an example)
```
Traceback (most recent call last):
  File "throwing.py", line 10, in <module>
    main()
  File "throwing.py", line 7, in main
    throws()
  File "throwing.py", line 4, in throws
    raise RuntimeError('this is the error message')
RuntimeError: this is the error message
```

**Comment by patrikbi** [comment]
Environment:


Request Method: GET
Request URL: http://logsearch.lab.local/oauth2/login

Django Version: 1.10.6
Python Version: 2.7.12
Installed Applications:
['app',
 'django.contrib.admin',
 'django.contrib.auth',
 'django_auth_adfs',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/webapps/logsearch/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/webapps/logsearch/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/webapps/logsearch/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/webapps/logsearch/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/webapps/logsearch/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/webapps/logsearch/local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/webapps/logsearch/local/lib/python2.7/site-packages/django_auth_adfs/views.py" in get
  19.         code = request.GET["code"]

Exception Type: TypeError at /oauth2/login
Exception Value: 'instancemethod' object has no attribute '__getitem__'

**Comment by patrikbi** [comment]
Internal Server Error: /oauth2/login
Traceback (most recent call last):
  File "/webapps/logsearch/local/lib/python2.7/site-packages/django/core/handler                                                                                                                                                             s/exception.py", line 42, in inner
    response = get_response(request)
  File "/webapps/logsearch/local/lib/python2.7/site-packages/django/core/handler                                                                                                                                                             s/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/webapps/logsearch/local/lib/python2.7/site-packages/django/core/handler                                                                                                                                                             s/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/webapps/logsearch/local/lib/python2.7/site-packages/django/core/handler                                                                                                                                                             s/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/webapps/logsearch/local/lib/python2.7/site-packages/django/views/generi                                                                                                                                                             c/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/webapps/logsearch/local/lib/python2.7/site-packages/django/views/generi                                                                                                                                                             c/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/webapps/logsearch/local/lib/python2.7/site-packages/django_auth_adfs/vi                                                                                                                                                             ews.py", line 19, in get
    code = request.GET["code"]
  File "/webapps/logsearch/local/lib/python2.7/site-packages/django/utils/datast                                                                                                                                                             ructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'code'"

**Comment by jobec** [comment]
It seems like the ADFS server isn't redirecting with a authorization code.

What did you configure as the redirect URL in ADFS?
In your browser, what is the URL you're redirected to after authenticating with ADFS?

**Comment by jobec** [comment]
Also, the ``REDIR_URI`` setting from your initial message looks wrong. It should be the URI configured in ADFS and be the URL pointing to your running django instance.

**Comment by patrikbi** [comment]
This is my first AD FS setup so very so really starting to think I have done the AD FS installation wrong. Gone over serveral guides and not figured it out yet.

**Comment by jobec** [comment]
Could you try the following?

1. Install the latest version from the master on github (so not from pypi)
1. Add debug logging to your django settings ([see here](http://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html))
1. Start Django using `manage.py runserver` from a console window
1. Trigger the issue and paste the full output from the console window here (or in a [github gist](https://gist.github.com/) and put the link here). So not the output in your browser, but from the console.

**Comment by patrikbi** [comment]
Hi!

Awsome I will try this later tonight!

Thank you

**Comment by patrikbi** [comment]
https://gist.github.com/patrikbi/8b6923fd72f87e35d54d6949d000cbe0

**Comment by jobec** [comment]
I think you still have the standard pypi version installed and not the one from master.

I also can't see the debug logging as it's only the back trace, not the entire console output.

**Comment by patrikbi** [comment]
https://gist.github.com/patrikbi/b710a81bf69a1e48769fa6fec588d5e2

**Comment by patrikbi** [comment]
Update: I woke upp in the middle of the night and realized I made a error in the settings. Now I get a new message.

System check identified no issues (0 silenced).
March 29, 2017 - 06:46:54
Django version 1.10.6, using settings 'LogSearch.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
DEBUG 2017-03-29 06:46:58,511 django_auth_adfs.backend django_auth_adfs was called but no authorization code was received
[29/Mar/2017 06:46:58] "GET /oauth2/login HTTP/1.1" 401 12


And the page says "Login failed"

**Comment by jobec** [comment]
I guess you're browsing to ``/oauth2/login`` directly while it's meant to be the redirection target for ADFS not the page to log you in. Logging in should be done by redirecting your user to ADFS, having them authenticate there and wait for the redirect.

You can do 2 things:
1. Detect that a user needs to log in in your django code somewhere and redirect them to the correct URL. You can get this URL by calling ``django_auth_adfs.util.get_adfs_auth_url()``
2.  Use the ``LoginRequiredMiddleware`` and have that middleware redirect you as soon as you go to a page of you site (except the login page of django)

**Comment by patrikbi** [comment]
Thank you for your help!

I added the LoginRequiredMiddleware and now it's working.

**Comment by patrikbi** [comment]
Looks like I was to quick on the trigger here. =(

Get the following internal error when trying to connect using Chrome (I have to enter the correct credentials when attempting to login on the AD FS server):
https://gist.github.com/patrikbi/9b255cbe2274ba481a67963d4917523b

URL:
https://logsearch.lab.local/oauth2/login?code=ch0Z8a3xikaYy0nu2dAL4Q.PJJKrtR61AgXALmS-pyKrz4Jod8.gPeOf8gmZMJETBU9KrwwG7OeP8M5eHvM0RI9LJ5HbxznOL6ItYLrOrYKMTtn_6aeeJ1-GbOl0IusCQPN2YmXz9h6ZEE2JPP-sH99hAo2iC1rogsc-afU0YdvHAWUukLKJ6UNwHQWxCyvc_Sm911DZIgmwhimsG806dkdDIFTwclvlfDJHctRSjZEoy5HSDpnmR1u8-C3qgmYRXaBmFEA8Uernxl9POtXni78nXX0eDZPfFA4jwr_QuHAr08JfjP7BeXLqFz3JIRktXyINW9sJBjMccdOYwIb3Y4MQRSQIw6HPIsqiKQh7ybuW7yVa6kaVop4CcsZJ4u0nLgoYBl6wQ

When trying to use IE I oddly just get a 400

**Comment by jobec** [comment]
```
...
DEBUG 2017-04-03 20:49:56,156 django_auth_adfs.backend :: token URL: https://dwsdc1.lab.local/adfs/oauth2/token
...
ConnectionError: HTTPSConnectionPool(host='dwsdc1.lab.local', port=443): Max retries exceeded with url: /adfs/oauth2/token (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7feab9a55e50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
- ``dwsdc1.lab.local`` is the correct FQDN of your ADFS server?
- Is it resolvable from the server django is running on? E.g. can you ping that address from that server?

**Comment by patrikbi** [comment]
Damn, why did I not think of this. I was using the wrong DNS server. :/ 

Moved on to the next thing to troubleshoot.
https://gist.github.com/patrikbi/913cad7c610af2eab07e5da326a21a31

**Comment by jobec** [comment]
Verify your ``CA_BUNDLE`` setting.

http://django-auth-adfs.readthedocs.io/en/latest/configuration.html#ca-bundle

Can only be the boolean values ``True`` or ``False`` or a string containing the path to a valid PEM encoded root CA certificate bundle.

**Comment by patrikbi** [comment]
Using CA_BUNDLE: False in the first example

If I change it to the PEM I created
https://gist.github.com/patrikbi/740b40c4e8d8c337d586e9ac21f8387e

Assume I made the PEM wrong.

**Comment by jobec** [comment]
Make sure it's a ``boolean`` value and not a string.
e.g.:
```python
AUTH_ADFS = {
    ...
    "CA_BUNDLE": False,
    ...
}
```
This is **wrong**:
```python
AUTH_ADFS = {
    ...
    "CA_BUNDLE": "False",
    ...
}
```
Else it will try to open the file ``False`` instead of disabling verification.

**Comment by patrikbi** [comment]
DEBUG 2017-04-04 09:07:03,947 django_auth_adfs.backend Received access token: <Removed>
INFO 2017-04-04 09:07:03,948 django_auth_adfs.backend Issued At claim (iat) cannot be in the future.

Checked NTP and time on both machines and they are in sync.

**Comment by jobec** [comment]
Same timezone?
If they are different, try putting them to the same zone.
If it's indeed triggering an issue, I need to look into taking timezone stuff into account.

**Comment by jobec** [comment]
You also stripped out the access token from the debug log. It's value can be decoded on https://jwt.io to see what it's issue time is and compare it with the logging timestamp.

**Comment by patrikbi** [comment]
DEBUG logtime 10:42:37

JWT:
"iat": 1491302561, (GMT: Tue, 04 Apr 2017 10:42:41 GMT)
auth_time": "2017-04-04T10:42:41.750Z"

**Comment by jobec** [comment]
If you compare the debug log time vs. the "issues at" time, you'll see the clock of your ADFS server is 4 seconds ahead (10:42:41) of the server that is running Django (10:42:37).

**Comment by patrikbi** [comment]
Time issue is now resolved.

Next error:
INFO 2017-04-04 11:43:17,535 django_auth_adfs.backend Invalid audience

ticket contains:
  "aud": "https://dwsdc1.lab.local/adfs/oauth2",

settings.py
   "AUDIENCE": "microsoft:identityserver:https://dwsdc1.lab.local/adfs/oauth2",

I also had the wrong issuer setting but fixed this and it's no longer complaining.

**Comment by patrikbi** [comment]
solved the above issue.

Next problem is:
ImproperlyConfigured: Claim not found in payload: 'given_name'. Check ADFS claims mapping.

Looks like I need to change some Claims. Will look in to this later today.

**Comment by patrikbi** [comment]
And I'm logged in. =)

**Comment by jobec** [comment]
If you can make a couple of screenshots of your adfs configuration I'll be happy to implement them in the documentation.

**Comment by patrikbi** [comment]
I will document and upload.
