### ISSUE TITLE
unsupported or invalid wheel

### ISSUE THREAD

**Issue by vpotter** [jobec/django-auth-adfs#12]
`pip install django-auth-adfs==0.1.2` fails with `django-auth-adfs is in an unsupported or invalid wheel` when trying to install on Python `3.6`. Installation works fine on Python `2.7`.

**Comment by jobec** [comment]
Could you try installing via PIP with the ``--no-binary`` option?
So something like
```
pip install django-auth-adfs==0.1.2 --no-binary :all:
```

**Comment by vpotter** [comment]
```pip install django-auth-adfs==0.1.2 --no-binary :all:``` works

**Comment by jobec** [comment]
The wheel on pypi indeed seems corrupted (it also contains directories form the 1.0.0 version for some reason.
I cannot delete the wheel on pypi and I also cannot overwrite it anymore.

I'll see how to fix this. Else I'll release a new 0.1.3 version.

**Comment by jobec** [comment]
I managed to delete the corrupt wheel package.

Could you try again to install it in a normal way? You might need to bypass the pip cache by adding `--no-cache-dir` to the command.

**Comment by vpotter** [comment]
> Could you try again to install it in a normal way?

It works now. Thanks!
