### ISSUE TITLE
The received resources parameter is invalid

### ISSUE THREAD

**Issue by egulatee** [jobec/django-auth-adfs#13]
Hi,

We are trying to configure ADFS SSO for Django using django-auth-adfs.
We believe we have configured things correctly however we get redirected back to the REDIRECT_URI with the following error

error_description	u"MSIS9602: The received 'resource' parameter is invalid. The authorization server can not find a registered resource with the specified identifier."
error	u'invalid_resource

Questions:
	How can we identify if this is an ADFS issue or a django-auth-adfs issue?
	Any guidance on how to either solve the issue or go about troubleshooting would be appreciated.

[DESKTOP_IP] = Ip of my desktop running nginx proxying to gunicorn.  Note:  Self Signed Certificates are being used.
[FQDN_OF_ADFS_SERVER] = FQDN of Adfs server
[RelyingPartyTrust] = Configured in ADFS and matches Django value
[ClientID] = Configured in ADFS and matches Django value

=====ADFS server configuration ==========

AllowedAuthenticationClassReferences : {}
AutoUpdateEnabled : False
DelegationAuthorizationRules :
EncryptionCertificateRevocationCheck : CheckChainExcludeRoot
PublishedThroughProxy : False
IssuanceAuthorizationRules : @RuleTemplate="AllowAllAuthzRule" => issue(Type =
"http://schemas.microsoft.com/authorization/claims/permit", Value="true");
SigningCertificateRevocationCheck : CheckChainExcludeRoot
WSFedEndpoint :
AdditionalWSFedEndpoint : {}
ClaimsProviderName : {}
IssuanceTransformRules :
ClaimsAccepted : {}
ConflictWithPublishedPolicy : False
EncryptClaims : True
Enabled : True
EncryptionCertificate :
Identifier : {https://[DESKTOP_IP]:10443/oauth2/login}
LastMonitoredTime : 12/31/1899 7:00:00 PM
LastPublishedPolicyCheckSuccessful :
LastUpdateTime : 12/31/1899 7:00:00 PM
MetadataUrl :
MonitoringEnabled : False
Name : Python
NotBeforeSkew : 0
EnableJWT : True
AlwaysRequireAuthentication : False
Notes :
OrganizationInfo :
ImpersonationAuthorizationRules :
AdditionalAuthenticationRules :
ProxyEndpointMappings : {}
ProxyTrustedEndpoints : {}
ProtocolProfile : WsFed-SAML
RequestSigningCertificate : {}
EncryptedNameIdRequired : False
SignedSamlRequestsRequired : False
SamlEndpoints : {}
SamlResponseSignature : AssertionOnly
SignatureAlgorithm : http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 
TokenLifetime : 0
AllowedClientTypes : Public
IssueOAuthRefreshTokensTo : NoDevice 

==========  Django configuration ==============

# checkout config.py for more settings
AUTH_ADFS = {
    "SERVER": "[FQDN_OF_ADFS_SERVER]",
    "CLIENT_ID": "[ClientID]",
    "RESOURCE": "[RelyingPartyTrust]",
    # Make sure to read the documentation about the AUDIENCE setting
    # when you configured the identifier as a URL!
    "AUDIENCE": "microsoft:identityserver:[RelyingPartyTrust]",
    "ISSUER": "http://[FQDN_OF_ADFS_SERVER]/services/trust",
    "CA_BUNDLE": "/code/CERT.pem",
    "CLAIM_MAPPING": {"first_name": "given_name",
                           "last_name": "family_name",
                           "email": "email"},
    "REDIR_URI": "https://[DESKTOP_IP]:10443/oauth2/login",
}

============================================

SERVER:
	parameter seems correct based on docs :  http://django-auth-adfs.readthedocs.io/en/latest/configuration.html#server

CLIENT_ID:
	http://django-auth-adfs.readthedocs.io/en/latest/configuration.html#client-id
	ADFS Admin confirm value is set correctly.

RESOURCE : 
	http://django-auth-adfs.readthedocs.io/en/latest/configuration.html#resource
	Set this to the name of the Relying Party Trust you configured in ADFS  (Do not see it in ADFS config provided)
	ADFS admin has confirmed it is set correctly.

AUDIENCE:
	http://django-auth-adfs.readthedocs.io/en/latest/configuration.html#audience
	Set this to the value of the aud claim your ADFS server sends back in the JWT token. If you leave this set to None this claim will not be verified.
	Changed to None, no difference

CA_BUNDLE
	http://django-auth-adfs.readthedocs.io/en/latest/configuration.html#ca-bundle
	Changed to True, no difference.

CLAIM_MAPPING
	http://django-auth-adfs.readthedocs.io/en/latest/configuration.html#claim-mapping
	Removed, no difference.

REDIR_URI:
	http://django-auth-adfs.readthedocs.io/en/latest/configuration.html#redir-uri
	Seems correct based on Django ADFS plugin & ADFS redirecting back to that page and displaying errors at that URL

**Comment by jobec** [comment]
The `RESOURCE` setting should match the **Identifier** parameter of the Relying Party trust in ADFS. So if I interpret your output correctly, it should be `https://[DESKTOP_IP]:10443/oauth2/login` 

More insight here:
https://github.com/nordvall/TokenClient/wiki/OAuth-2-Authorization-Code-grant-in-ADFS

It's still on my todo list to add screenshots of the ADFS config, but I'll need to rebuild my test setup before I can do that...

**Comment by backside180** [comment]
I'm getting this exact same issue.

I have also tried various configuration changes to get this to work but it still comes back with:

> Request Method: 	GET
Request URL: 	http://webserver.local/oauth2/login?error=invalid_resource&error_description=MSIS9602%3a+The+received+%27resource%27+parameter+is+invalid.+The+authorization+server+can+not+find+a+registered+resource+with+the+specified+identifier.
Django Version: 	1.11.1
Exception Type: 	MultiValueDictKeyError
Exception Value: 	"'code'"

My setting.py is configured as follows:

> AUTH_ADFS = {
	"LOGIN_EXEMPT_URLS" : ["^admin/$", "^inventory/$", "^inventory/servers/$"],
	"SERVER" : "adfsserver.local",
	"CLIENT_ID" : "d52803f4-8e76-46b2-a6f8-7c7b0996173f",
	"RESOURCE" : "SPSC",
	"AUDIENCE" : "microsoft:identityserver:http://webserver.local/oauth2/login",
	"ISSUER" : "https://adfsserver.local/adfs/services/trust",
	"CA_BUNDLE" : False,
	"CLAIM_MAPPING" : {"first_name": "given_name",
					"last_name": "family_name",
					"email": "email"},
	"REDIR_URI" : "http://webserver.local/oauth2/login",
	"LOGIN_REDIRECT_URL": "https://adfsserver.local/adfs/ls"
}

I think I have my ADFS Server setup correctly but I don't have anything to compare this with. 

Get-AdfsClient output:

> RedirectUri : {http://webserver.local/oauth2/login}
Name        : SPSC
Description :
ClientId    : d52803f4-8e76-46b2-a6f8-7c7b0996173f
BuiltIn     : False
Enabled     : True
ClientType  : Public

Relying Party Trust:

> Display Name: SPSC
Type: WS-Trust / SAML / WS-Federation
Identifier: http://webserver.local/oauth2/login
Remaining Settings left at default values.

Output from: Get-AdfsRelyingPartyTrust -Name "SPSC"

> AllowedAuthenticationClassReferences : {}
AutoUpdateEnabled                    : False
DelegationAuthorizationRules         :
EncryptionCertificateRevocationCheck : CheckChainExcludeRoot
PublishedThroughProxy                : False
IssuanceAuthorizationRules           : @RuleTemplate = "AllowAllAuthzRule"
                                        => issue(Type = "http://schemas.microsoft.com/authorization/claims/permit",
                                       Value = "true");
SigningCertificateRevocationCheck    : CheckChainExcludeRoot
WSFedEndpoint                        :
AdditionalWSFedEndpoint              : {}
ClaimsProviderName                   : {}
IssuanceTransformRules :
 @RuleTemplate = "LdapClaims"
 @RuleName = "given_name"
                                       c:[Type ==
                                       "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname",
                                       Issuer == "AD AUTHORITY"]
                                        => issue(store = "Active Directory", types =
                                       ("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"), query =
                                       ";givenName;{0}", param = c.Value);
@RuleTemplate = "LdapClaims"
@RuleName = "family_name"
                                       c:[Type ==
                                       "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname",
                                       Issuer == "AD AUTHORITY"]
                                        => issue(store = "Active Directory", types =
                                       ("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"), query =
                                       ";sn;{0}", param = c.Value);
@RuleTemplate = "LdapClaims"
@RuleName = "email"
                                       c:[Type ==
                                       "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname",
                                       Issuer == "AD AUTHORITY"]
                                        => issue(store = "Active Directory", types =
                                       ("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"), query =
                                       ";mail;{0}", param = c.Value);
ClaimsAccepted                       : {}
ConflictWithPublishedPolicy          : False
EncryptClaims                        : True
Enabled                              : True
EncryptionCertificate                :
Identifier                           : {http://webserver.local/oauth2/login}
LastMonitoredTime                    : 01/01/1900 00:00:00
LastPublishedPolicyCheckSuccessful   :
LastUpdateTime                       : 01/01/1900 00:00:00
MetadataUrl                          :
MonitoringEnabled                    : False
Name                                 : SPSC
NotBeforeSkew                        : 0
EnableJWT                            : True
AlwaysRequireAuthentication          : False
Notes                                :
OrganizationInfo                     :
ImpersonationAuthorizationRules      :
AdditionalAuthenticationRules        :
ProxyEndpointMappings                : {}
ProxyTrustedEndpoints                : {}
ProtocolProfile                      : WsFed-SAML
RequestSigningCertificate            : {}
EncryptedNameIdRequired              : False
SignedSamlRequestsRequired           : False
SamlEndpoints                        : {}
SamlResponseSignature                : AssertionOnly
SignatureAlgorithm                   : http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
TokenLifetime                        : 0
AllowedClientTypes                   : Public
IssueOAuthRefreshTokensTo            : NoDevice


Any Help on this would be greatly appreciated, I don't want to have to switch to django-auth-ldap I would prefer to use ADFS.

**Comment by jobec** [comment]
> Relying Party Trust:
> 
>     Display Name: SPSC
>     Type:         WS-Trust / SAML / WS-Federation
>     Identifier:   http://webserver.local/oauth2/login
> 
> My setting.py is configured as follows:
> 
>     AUTH_ADFS = {
>     ...
>     "RESOURCE" : "SPSC",
>     ...
>     }
> 

Try setting the `RESOURCE` setting to `http://webserver.local/oauth2/login` once and see if that works.

I'll try to make some more documentation about configuring ADFS soon.

**Comment by backside180** [comment]
Yes that fixed my initial problem, I now see the login screen, however now when I login I get redirected back to:

> http://webserver.local/oauth2/login?code=Bccl7WIG40-zZFaPqP_HuQ.Q-KMO2Gy1AgOAEgFBwtlOR43hS0.M6RZ0_wJY5r9MWRbrDxymnM3dsaQuwR-wt4TXmD_BYUV5U8BJe0qrtw8I21_9gE8ivXHZpSNf02cf9yD_4Ey4vLGSQvMgk4_DUpmNV_3PBvada8xvHX_Z4DePeQbLGxiUcwXu5wXJAjM6qZ3bmr16cA1jd-uFpWbCMm-CpgNjhrSpPVRIzG3Wllckm9W7AMvWGH8FbxF0UkWx_5JUt4PZQfyR1NgC_nIbSFeelHOtucfjLLCJDuBfDJZZ_fzCiGtPnnxaQTha_AriJXFUG3I225A2EryYRVaB6XmBbYU08kbMM3t8RsvUFKIDFlzNNAql3xN9lm9ys_Ofzd8AH-ngw

but am presented with 

> Login failed

I assume this is due to my ADFS Claim rule configuration. 

Can you shed any-light on how the ADFS Side rules should be configured.

Thanks for your help so far.

**Comment by jobec** [comment]
Could you try the following?

1. Install the latest version from the master on github (so not from pypi)
1. Add debug logging to your django settings ([see here](http://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html))
1. Start Django using `manage.py runserver` from a console window
1. Trigger the issue and paste the full output from the console window here (or in a [github gist](https://gist.github.com/) and put the link here). So not the output in your browser, but from the console.

**Comment by backside180** [comment]
I'm using Apache so dumped the debug information to a file.
Is this what you are expecting to see:

> Retrieving ADFS metadata file from https://adfsserver.local/FederationMetadata/2007-06/FederationMetadata.xml
Authorization code received. Fetching access token.
:: token URL: https://adfsserver.local/adfs/oauth2/token
:: authorization code xx: Bccl7WIG40-zZFaPqP_HuQ.7eTUUHGy1AgeAAzP0CY89qPUCiY.li5wTW5pLRyhzAH_h95VBKZxOllpnX4A2li3o-LglqyND0bsa7aGTWhF-EozUJcfa9Tj4luPl08i9gLl
LFoZWTxhcoCTOIgUGSsNdmQSmOmGYJqF-0TDYGlv28dplr9_ZtUqBKU-gvQZMXTqobOUQZxQM54onLNhjvAdsWohQeWaBD9m_WrNVpysGXKshsSJuZ7GSe31ICO3rECin36SIl6vvCv_dvxcm7A_Im0wwvzH8
bAg-DQiHOu_XEilPKtsZUE34umXZ6urjyve24dBIbX-R4G4tcOYDSie9IkX_rNeXTET203xpgqmHMIEsU4uEXgg-977e0-aAmw7hFZL5g
Received access token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlNPTW5qbTByQXljalVTWGdjbVI0VXk0SDRQcyJ9.eyJhdWQiOiJodHRwOi8vc2NpbmYtd2ViMDEuc3BzYy5oZHMuY
29tL29hdXRoMi9sb2dpbiIsImlzcyI6Imh0dHA6Ly9TQ0lORi1BREZTMDEuU1BTQy5IRFMuQ09NL2FkZnMvc2VydmljZXMvdHJ1c3QiLCJpYXQiOjE0OTczNjc5MTIsImV4cCI6MTQ5NzM3MTUxMiwid2luYW
Njb3VudG5hbWUiOiJTUFNDXFxqaHV0Y2hpbnNvbiIsImF1dGhfdGltZSI6IjIwMTctMDYtMTNUMTU6MzE6NTEuODU0WiIsImF1dGhtZXRob2QiOiJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YWM6Y2x
hc3NlczpQYXNzd29yZFByb3RlY3RlZFRyYW5zcG9ydCIsInZlciI6IjEuMCIsImFwcGlkIjoiZDUyODAzZjQtOGU3Ni00NmIyLWE2ZjgtN2M3YjA5OTYxNzNmIn0.ItmeG6NgRlyRSshNXymMMtIuzPsb1MiP
kBjpnFRiLdtW51oHYSDRWOqiqknKsounZZJs1l08TZK1SJJjnjyzZAcsyRFrUw939gwGEK4tJVsEHT97ypLOLhj4-ynOx-W2fB4-gNac1an_wqnYGQxyCxMt2kzGPzTPxHAtOP2027VwEI1U2rBFaDY6Ht4Zv
HrlOMCvKCQCZi5zXjVpPeDxDBbzP8mlwuy3bH18VV20GJP7yXLyKhg5r1pmQn9csrBQ0mBilRMHu9hQ3-aoyIdF4y8xRGFPoLRpgalGDgMi5Zv7x7mO-arLk00ipuZ9zce2E_S_-sU0PsiP0R6_o9LewA
Invalid issuer

**Comment by jobec** [comment]
Your issuer is configured wrong. You can take the access token from the output above, decode it on https://jwt.io and see what the issuer is.

**Comment by jobec** [comment]
@egulatee any update whether your issue is resolved?

**Comment by backside180** [comment]
I tried this but the decoder give me a strange output.
Please confirm what I should be pasting in to the decoder.

Also please note that I have been replacing my real FQDN with adfsserver.local and webserver.local my real server names contain, adfs01 and web01, is this what you are seeing?

**Comment by jobec** [comment]
Issuer seems to start with `http://` instead of `https://` and the server's fqdn is in uppercase (don't know if it's case sensitive. Never actually tested)

**Comment by backside180** [comment]
OK I have updated my ADFS Federation Services Properties to use https and have changed the FQDN to lowercase.

I'm now getting "Invalid audience" in the debug log

I'm still not sure how or what you did to decode the JWT as I say when I paste in the following I get random characters back in the header etc. 

`Bccl7WIG40-zZFaPqP_HuQ.sJjfwYiy1AgHAF1aTcFdeGIUuWI.KWG_y_RiR3bWg2IRZxJLfxnvIPcgjg5jTlWAhW2FHCieQSkPd9DkKup7cPKUU_SrGptNmQVSYSnOygFlO-
nxPHwJFPJH-Ax5TybJ3qdlmqhCFow_UokPHpWkH-S1SWpoeGnuhB1T8dKwRYu37NGXO5Gma9QyKZipUidW-pgw8f2zIpO3LoY6qGaiCaN8sKQU7C4KhvyC9qh3ZdeoVNEoffjT7AkidvYhzEhoHUFmDJ99dwL
vLTARMWNqwXifATtW7adnQ5ti7ngOWw0XrYEwf6PtNAMk6FI-Y0lXxyMjcv4X7X21-NlkA5YNQckxnEUPk3Qx_kmnWhzjCfmbkgjhiQ`

Could this issue be related to me running django-auth-adfs with the following setting:
> "CA_BUNDLE" : False,

**Comment by jobec** [comment]
That string you pasted is the `authorization code` that is used to fetch the access token.
The actually retrieved access token is in the logs after `Received access token: `. I removed it from you reply above because it contained the actual addresses of your servers.

This token you should be able to decode on https://jwt.io

**Comment by backside180** [comment]
OK understood, Thanks for that.

I have just checked and now the 'iss' is https and the server name is lowercase. 

Should the "aud" value match the "AUDIENCE" in settings.py ?

**Comment by jobec** [comment]
Indeed

**Comment by backside180** [comment]
Jobec, I have made some good progress thanks for your help today. 

My final issue relates to the ADFS  claims listed in "CLAIM_MAPPING" within settings.py not being viable in the JWT payload. 

> ImproperlyConfigured at /oauth2/login
Claim not found in payload: 'email'. Check ADFS claims mapping.

I'm unsure how ADFS needs to be configured, I have tried a number of different configuration but still no success. 

The "winaccountname" is come across but that all.

Do you have any pointers on how ADFS should be configured to enables these in the payload of the JWT?

**Comment by egulatee** [comment]
@Jobec I will begin working on this now and let you know.    Appreciate the rapid response.

**Comment by egulatee** [comment]
@jobec I did your suggested change, I will work with ADFS admins to confirm settings are matching in both Django & ADFS.
Question:  Would it matter if it's an IP address or different port (10443) or self-signed cert?

**Comment by egulatee** [comment]
@jobec After changing the RESOURCE setting to https://[DESKTOP_IP]:10443/oauth2/login , it seems to still be an issue.

1-  Is the setting section (Relying Party Trust ) backside180 refers to included within Get-AdfsRelyingPartyTrust -Name "SPSC" or are they separate values and just so happen to somewhat overlap?

2-  Any recommendation on further troubleshooting?  

3-  Comparing with Backside180's settings, we don't have any IssuanceTransformRules, would that matter?

4-  Does the request URL need to match the RESOURCE?  Because it doesn't at the moment.  (Reverse Proxy is not rewriting the URL atm)

**Comment by jobec** [comment]
I'm in the course of setting up my test environment again. I'll try to get some step by step instructions in the next couple of days.

**Comment by egulatee** [comment]
@jobec Thank you, appreciate it, ADFS screenshots would definitely help.

**Comment by egulatee** [comment]
@jobec   I wonder if it's not my setup.
I am running an httpd proxy and gunicorn appserver in docker containers in a virtual machine (Desktop_ip).

I have configured things using my DESKTOP_IP which is port forwarded to my httpd server running in a container, however, the error returned by ADFS shows a RequestURL coming from my pythonappserver.  (Which ADFS has no knowledge of, I only provided desktop ip port fwd'ed to httpd)
  
Q:  How should the settings differ in a multi tier configuration (public facing webserver proxying a django appserver?) .   
Q:  Are there settings that should use the pythonappserver ip and others the public facing proxy?
Q: Should the RESOURCE be the public facing URL from AppServer

**Comment by egulatee** [comment]
Yeah, hacking up my gunciron server to response to https requests as [DESKTOP_IP]:100443 so ADFS sees the RESOURCE value as the request URL didn't change anything.  Now I'm really out of ideas unfortunately.

**Comment by backside180** [comment]
Let me try to summarise my configuration which now appears to be working:

My settings.py file contains the following:

> AUTH_ADFS = {
	"LOGIN_EXEMPT_URLS" : ["^admin/$", "^inventory/$", "^inventory/servers/$"],
	"SERVER" : "[adfs server FQDN]",
	"CLIENT_ID" : "d52803f4-8e76-46b2-a6f8-7c7b0996173f",
	"RESOURCE" : "http://[webserver FQDN]/oauth2/login",
	"AUDIENCE" : "http://[webserver FQDN]/oauth2/login",
	"ISSUER" : "https://[adfs server FQDN]/adfs/services/trust",
	"CA_BUNDLE" : False,
	"CLAIM_MAPPING" : {"first_name": "given_name",
						"last_name": "family_name",
						"email": "email"},
	"REDIR_URI" : "http://[webserver FQDN]/oauth2/login",
	"LOGIN_REDIRECT_URL": "http://[webserver FQDN]/"
}

See this handy guide to assist in the setup of ADFS - http://www.gi-architects.co.uk/2016/04/setup-oauth2-on-adfs-3-0/

"ISSUER" should match the ADFS Federation Service identifier (AD FS Management (UI) -> Federation Service Properties -> General (Tab) -> Federation Service identifier (Field) )

"CLIENT_ID" is defined when you run the following command when setting up your ADFS Relying Party Trust.
`Add-AdfsClient -RedirectUri "https://appredirect.local" -ClientId "5d51f771-b86a-419e-ad25-27696eafc02b" -Name "My app entry"`

**ADFS Claim rules**
To ensure the correct fields are sent back to your app in the JTW you need to add some claim rules, I got mine working by using the following configuration within the ADFS Relaying Party Trust.

So within "Edit Claim Rules" for your relaying party trust configure the following rules (this is based on my Settings -> CLAIM_MAPPING)

(For ease I created my claim rules to have names that represent my claim mapping name)

Rule1: User account name (Domain\user Format)  (This is not in the CLAIM_MAPPING list but it is a required as a field in the JTW)

Rule Template | Claim Rule Name | Incoming claim type | Selection 
------------ | ------------- | -------------- | --------------- 
Pass Through or Filter Incoming Claim  | winaccount | Windows account name | Pass through all claim values 

Rule2: (email)

Rule Template | Claim Rule Name | Attribute store | LDAP Attribute | Outgoing Claim Type
------------ | ------------- | -------------- | --------------- | --------------
Send LDAP Attributes as Claim  | email | Active Directory | E-Mail-Addresses | E-Mail Address 

Rule3: (first_name)

Rule Template | Claim Rule Name | Attribute store | LDAP Attribute | Outgoing Claim Type
------------ | ------------- | -------------- | --------------- | --------------
Send LDAP Attributes as Claim  | first_name | Active Directory | Given-Name | Given Name 

Rule4: (last_name)

Rule Template | Claim Rule Name | Attribute store | LDAP Attribute | Outgoing Claim Type
------------ | ------------- | -------------- | --------------- | --------------
Send LDAP Attributes as Claim  | last_name | Active Directory | Surname | Surname

Rule5: (group) ( for every group you want to create in the django users model create a rule as per the following ) 

> Notes: django-auth-adfs is expecting a "group" field in the JTW that's returned so we have to create this in our claim rules. 
> Also the group value returned by this claim must exist as a created group in the Django Admin, else auth-adfs can't add the user to the group.

Rule Template | Claim Rule Name | User's Group | Outgoing Claim Type | Outgoing claim value
------------ | ------------- | -------------- | --------------- | --------------
Send Group Membership as a Claim  | group_[GroupName] | [AD Group] | Group | [Djanogo Admin Group Name]

I hope the above helps.

Having tested this I have a number of observations and comments I would like to raise, I will open another issues for these.

**Comment by jobec** [comment]
Thanks for the details. I'll try to have them implemented in the ADFS config guide I'm about to write.

Also, don't hesitate to open issues if you think something can be improved. I'll be happy to have a look at it.

**Comment by egulatee** [comment]
@backside180 Thank you for your settings.  I have matched them and I am still getting the same error.

AUTH_ADFS = {
#    "SERVER": "adfs.yourcompany.com",
    "SERVER": " ADFSSERVER FQDN ",

#    "CLIENT_ID": "your-configured-client-id",
    "CLIENT_ID": "[CLIENT_ID_CONFIGURED_IN_ADFS]",
    "RESOURCE": "https://[DESKTOP_IP]:10443/oauth2/login",
    # Make sure to read the documentation about the AUDIENCE setting
    # when you configured the identifier as a URL!
    "AUDIENCE": "https://[DESKTOP_IP]:10443/oauth2/login",
    
    "ISSUER": "http://[ADFSSERVER FQDN]/adfs/services/trust",
    "CA_BUNDLE": False,
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
    "REDIR_URI": "https://[DESKTOP_IP]:10443/oauth2/login",
    "LOGIN_REDIRECT_URL": "https://[DESKTOP_IP]:10443/"
}

Using chrome, Hitting the APP URL redirects to ADFS.  I see the HTTP Request to ADFS (Seen via  Chrome Network Traffic):
https://[ADFS_FQDN]/adfs/oauth2/authorize?response_type=code&client_id=[CLIENT_ID]&resource=https://[DESKTOP_IP]:10443/oauth2/login&redirect_uri=https://[DESKTOP_IP]:10443/oauth2/login

which then redirects to (As per Chrome Network Traffic)

https://[DESKTOP_IP]:10443/oauth2/login?error=invalid_resource&error_description=MSIS9602%3a+The+received+%27resource%27+parameter+is+invalid.+The+authorization+server+can+not+find+a+registered+resource+with+the+specified+identifier.

Again, [DESKTOP_IP] = My PC's IP.  I have Gunicorn running in a container listening on [DESKTOP_IP 
]:10443.  

So, aside from the claim rules that haven't been defined in ADFS, it seems like the settings match yours.
I did not run the latest Django-auth-adfs code via github.  (But that seemed required once you moved past the RESOURCE failure issue, I am using the version in pypi)

**Comment by egulatee** [comment]
Interestingly enough I am getting the same error when submitting same request via curl.  I have requested to create a new RPT following guide suggested by @backside180.

"See this handy guide to assist in the setup of ADFS - http://www.gi-architects.co.uk/2016/04/setup-oauth2-on-adfs-3-0/"

If that fails, I am will wait for ADFS screenshots from @jobec.  

Thanks again both of you for your help to date, definitely above and beyond.

**Comment by jobec** [comment]
I've just now added extra documentation.

Have a look here and let me know if it helps: http://django-auth-adfs.readthedocs.io/en/latest/adfs_config_guide.html

**Comment by egulatee** [comment]
@jobec  Thank you, 
What is the minimum ADFS version that should be used?  
https://en.wikipedia.org/wiki/Active_Directory_Federation_Services

ADFS 1.0 - Windows Server 2003 R2 (additional download)
ADFS 1.1 - Windows Server 2008 and Windows Server 2008 R2.
ADFS 2.0 - Windows Server 2008 and Windows Server 2008 R2 (download from Microsoft.com)
ADFS 2.1 - Windows Server 2012.
ADFS 3.0 - Windows Server 2012 R2.
ADFS 4.0 - Windows Server 2016.

**Comment by jobec** [comment]
OAuth2 support is only available since ADFS 3.0

http://django-auth-adfs.readthedocs.io/en/latest/install.html#requirements

**Comment by egulatee** [comment]
@jobec Thank you very much for the instructions.  
Based on your referral to http://blog.scottlogic.com/2015/03/09/OAUTH2-Authentication-with-ADFS-3.0.html, I presume this plugin the public (user-agent) OAuth2 client profile?

**Comment by jobec** [comment]
It's the OAuth2 authorization code flow with a public client type indeed. It's the only thing adfs 3.0 supports.

Also, the scope of this package is ADFS and **only** ADFS. So it's by no means meant as a general OAuth2 client.

**Comment by egulatee** [comment]
@jobec Thanks again.  I think with all @backside180 and your help we're in a position to try again.

**Comment by egulatee** [comment]
@jobec  Your instructions were extremely helpful, thank you, following those gets us beyond the errors we were getting.
