### ISSUE TITLE
Integrating this into a system

### ISSUE THREAD

**Issue by K-Willem** [jobec/django-auth-adfs#15]
Could you perhaps provide any help with setting this up. 
Previously when implementing a SAML2 setup, I would define endpoints (/ls and /acs) in the AD server to add a relying party trust. What would the equivalent be for setting this up for ADFS 3?

I have the settings file update with the library etc, and I guess the next step would be pointing it to the correct AD server and getting that AD to add the solution as a Relying Party?
I'd appreciate any help in the matter, I think I might just be missing something small here.
Environment is python 3.5, Django 1.10 and ADFS 3.0

**Comment by jobec** [comment]
I've just now added extra documentation for issue #13 

Have a look here and let me know if it helps: http://django-auth-adfs.readthedocs.io/en/latest/adfs_config_guide.html

**Comment by K-Willem** [comment]
Thanks @jobec this helped a lot
