### ISSUE TITLE
Invalid ADFS token signing certificate

### ISSUE THREAD

**Issue by egulatee** [jobec/django-auth-adfs#19]
Hi,

Now that we have our resources correctly configured we are getting the following issue when CA_BUNDLE = False

Exception Type:	ImproperlyConfigured
Exception Value:	Invalid ADFS token signing certificate

Looking at the code, it seems to relate to the load_pem_x509_certificate(certificate, backend)
method in backend.py

I am using Python 2.7.13.

**Comment by jobec** [comment]
Try leaving the setting `SIGNING_CERT` unconfigured, or set it to the boolean value `True`. That wil auto load the certificate from the ADFS server.

If you do want to specify one, make sure it's in PEM format. And when loading it from a string, make sure not to add extra spaces and don't remove the header an footer.

**Comment by egulatee** [comment]
@jobec 

-  SIGNING_CERT was not set.
-  Setting SIGNING_CERT to true gets me the original error reported (Invalid ADFS token signing certificate)
-  Setting SIGNING_CERT to a path where the public PEM cert for ADFS I now get a "Login failed"! with no errors in the Django logs

I verified it's in PEM format...

.PEM = The PEM extension is used for different types of X.509v3 files which contain ASCII (Base64) armored data prefixed with a “—– BEGIN …” line.

**Comment by egulatee** [comment]
@jobec 

1-  After changing django-auth-adfs.backends.py to use os.linesep instead of "\n" I get the Login failed error from   (django-auth-adfs.views.py).    (I am running on linux)

2-  After setting verify to false in (django-auth-adfs.backends.jwt.decode()), I am actually getting some sort of token.  However PYJWT states it is ill-advised to do this.
https://pyjwt.readthedocs.io/en/latest/usage.html#registered-claim-names

**Comment by jobec** [comment]
What linux distribution/version are you running? Because \n should be the line separator on linux...

As for the verification issue of the token, it seems to indicate that the certificate you point to is not the signing certificate used on your ADFS server. Like stated, if you set the SIGNING_CERT setting to True, you should not have this problem because this certificate will be fetched from the ADFS. metadata file.

The code also doesn't read some database table directly, it just uses the django user model to manipulate users.

To further troubleshoot, follow the troubleshooting part in the documentation and provide the **full** logging output up to the point of the login error (console output if testing with the django runserver command, error log if using apache, ...) Put it in a gist a put the link here.

**Comment by egulatee** [comment]
I tried the following distributions:  Alpine Linux, Ubuntu, Debian and with either of them "\n" I get a failure.  

If you change usestring to true in the pasted code, it works for me, else I get the "Invalid ADFS token signing certificate" error.
https://gist.github.com/egulatee/ed4dd240dc857fd85344cf92b803af1c

Yeah, I see Django-auth-adfs doesn't directly read the database table.  I need to dig into our settings.  I don't see this as a Django-auth-adfs issue.  Has to with the auth stuff (django.contrib.auth), which I don't understand and if I remove it it from INSTALLED_APPS I get missing permission class/object.  

Questions:  Are you required to have django.contrib.auth in INSTALLED_APPS?  
Can we use django-auth-adfs for authorization?  (I do see the groups in the token).

**Comment by jobec** [comment]
I'm afraid there's not really any other way but creating the users in a database. It's the way Django works.

If, for some reason you cannot change your main database, there's also a way to [route the queries to a different database](https://docs.djangoproject.com/en/1.11/topics/db/multi-db/#using-routers).

**Comment by egulatee** [comment]
Okay, well, once we added the tables it started working for us.

I think we'll be able to address item 2 and 3 on our end without code changes, but item 1 (Invalid ADFS token signing certificate) seems like it will require a code change in django-auth-adfs.  Is there any value in trying to submit a code fix or do you expect that's related to item 2?   

Thanks again for your tremendous support getting things working.

**Comment by jobec** [comment]
To troubleshoot the certificate loading issue. Could you run the following script and provide me with the output?

```python
import os
import platform

from cryptography.hazmat.backends.openssl.backend import backend
from cryptography.x509 import load_pem_x509_certificate

base64_cert = "MIIDCTCCAfGgAwIBAgIJALLjs7wGmYSvMA0GCSqGSIb3DQEBBQUAMBsxGTAXBgNV" \
              "BAMMEGFkZnMuZXhhbXBsZS5jb20wHhcNMTYwMjE1MjAyNDQxWhcNMjYwMjEyMjAy" \
              "NDQxWjAbMRkwFwYDVQQDDBBhZGZzLmV4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0B" \
              "AQEFAAOCAQ8AMIIBCgKCAQEAy3JZC0ZF+8XpDQxQQDZEtmThOLnhld1TlLTBSEX7" \
              "lLLoDvlTVfop3LgWhdGhW1gM3Wa47oR3ni3JoXrbky+cAkMkslzu+p4xMS1ApZAp" \
              "ZUFh9ZL9eEXrvqZLYG0N20ffHkKd8XVN4w5nYQWHxp2uSECrStVAnL2m6DH1/Tla" \
              "DQAmrmaye+djXAxZjR6m/SQxQXOn6tLL9BMEF/UVt8GocSuATJdrXaKg9ubwR3j7" \
              "GRfRNNy1v+5LYfcRVFrFmupbL/6k8fUHeQ1qKNAhAvpcZl+4df1phUZJMnwcQncX" \
              "I3zqypz8bTTjTvu//iKr2U7Ih3TJdf/F51lPF0JaVB30jQIDAQABo1AwTjAdBgNV" \
              "HQ4EFgQUkbP4sH/t1YR+8DLC1+xHyAYEohQwHwYDVR0jBBgwFoAUkbP4sH/t1YR+" \
              "8DLC1+xHyAYEohQwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEAuMkH" \
              "KIurKQsktlaOebbPnpz1iqKUoSM8Vvf6TqX4hf1gIxoQJfVUdoktNCwHt+n/Fzvt" \
              "gzuHbigBdHKVQx7wlPc4dBRNmfqtOwpgtdrXq9suDjiPZHsEhui9Ak4ufXxzSUzx" \
              "KBc7RO0FWqgEMNVc5pKAWV9SN5e6nuH0uJnfj3f1EgVN8ia1TXkZiOOUMPpPOToJ" \
              "kyXR6FepOSOQRXPUoN2wozj4KbJBtpKQk0niMf5rPzN1hsNokt2HtVlcnZ25NV42" \
              "SEtFTMAxlamUZ0PhC2H9nxDo3dN8KS44fT4hBx5FUaUffetl4Q5ebrJ1IoBNZ6+S" \
              "aK7TCdKeEyDaHh6/Dg=="

pem_cert = ["-----BEGIN CERTIFICATE-----"]
no_of_slices = int(len(base64_cert) / 64)
for i in range(0, no_of_slices + 1):
    pem_cert.append(base64_cert[i * 64:(i + 1) * 64])
pem_cert.append("-----END CERTIFICATE-----")

n_line_cert = "\n".join(pem_cert)
os_line_cert = os.linesep.join(pem_cert)

print("Python:             %s" % platform.python_version())
print("Platform:           %s" % platform.platform())
print("OpenSSL version:    %s" % backend.openssl_version_text())
print("OS line ending:     %r" % os.linesep)
print("Strings equal:      %s" % (n_line_cert == os_line_cert))

try:
    n_line_cert = load_pem_x509_certificate(n_line_cert.encode(), backend)
    print("Certificate serial: %s" % n_line_cert.serial_number)
except Exception as e:
    print(e)

try:
    os_line_cert = load_pem_x509_certificate(os_line_cert.encode(), backend)
    print("Certificate serial: %s" % os_line_cert.serial_number)
except Exception as e:
    print(e)
 ```
Should give something like this
```
Python:             3.5.3
Platform:           Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.3.1611-Core
OpenSSL version:    OpenSSL 1.0.1e-fips 11 Feb 2013
OS line ending:     '\n'
Strings equal:      True
Certificate serial: 12890344178610439343
Certificate serial: 12890344178610439343
```

**Comment by egulatee** [comment]
jobec,

Here you go.

Python:                  2.7.13
Platform:                Linux-4.4.66-boot2docker-x86_64-with-Ubuntu-17.10-artful
OpenSSL version:         OpenSSL 1.0.2g  1 Mar 2016
Cryptography version:    1.7.1
OS line ending:          '\n'
Strings equal:           True
Certificate serial: 12890344178610439343
Certificate serial: 12890344178610439343

**Comment by jobec** [comment]
Ok, that indicates there's no issue with line endings. Unless the ouput is from a different host then the one django runs on.

What's the content of the metadata file on your adfs server? It's located at the url `https://ADFS-SERVER/FederationMetadata/2007-06/FederationMetadata.xml`. It looks like the token signing certificate isn't in there or at a different location. You can mail it to me if you cannot make it public.

**Comment by egulatee** [comment]
jobec,

No, that is the host that runs Django.

I will have a look at https://ADFS-SERVER/FederationMetadata/2007-06/FederationMetadata.xml
Should that signing certificate match the one returned when you do https:// requests?

**Comment by jobec** [comment]
The certificate on this xml path is being taken from that file:
https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/backend.py#L75

It's not the https certificate, it's the certificate configured here: https://technet.microsoft.com/en-us/library/dn781426(v=ws.11).aspx

The array vs. string stuff: in the end it's always a string. It's just that in needs to be converted to the right format. From the xml file, it's just a long base64 encoded string. It's lacking the needed headers and the lines should be max 64 characters. Hence the code splits that string into 64 char pieces, adds a header an footer and joins them with line endings. That then gets fed to openssl through the cryptography package and afterwards to the JWT package.

**Comment by jobec** [comment]
I don't know if this issue is still relevant, but there was a bug that caused some token validation issues (873f9da09144a679935c6f7d079dab2dd13ed569). Because of that version 0.2.0 has been released.

Please let me know if your issue is fixed or whether it's not relevant anymore.
