### ISSUE TITLE
'login failed'

### ISSUE THREAD

**Issue by john-michael-murphy** [jobec/django-auth-adfs#22]
Hey there! Not sure if this is a bug or if this is user error (probably the latter), but I'm trying to integrate this application with Davidson College's ADFS. 

I've configured relying party trust and added AUTH_ADFS to settings.py, but upon calling /oauth2/login, we get a simple "login failed." With verbose debugging on, we receive the error ``django_auth_adfs.backend django_auth_adfs was called but no authorization code was received``

My assumption is that this is the link that should redirect us to our ADFS login page. Is this assumption incorrect? 

Config settings below. 

```
AUTH_ADFS = {

    "SERVER": "sso.example.com",
    "CLIENT_ID": "django.example.com",
    "RESOURCE": "django.example.com",
    # Make sure to read the documentation about the AUDIENCE setting
    # when you configured the identifier as a URL!
    "AUDIENCE": "microsoft:identityserver:django.example.com",
    "ISSUER": "https://sso.example.com/adfs/services/trust",
    "CA_BUNDLE": False,
    "CLAIM_MAPPING": { "emailaddress": "emailaddress",
                      "givenname": "givenname",
                      "surname": "surname",
                      "Group": "Group",
                      "windowsaccountname": "windowsaccountname",
                      "groupsid": "groupsid",
                      "title": "title",
                      "department": "department" },
    "USERNAME_CLAIM": "winaccountname",
    "GROUP_CLAIM": "group",
    "REDIR_URI": "http://django.example.com/oauth2/login",

}
```

Thank you for your help and patience with my ignorance!

**Comment by jobec** [comment]
Your remark is both a feature request and a piece of missing documentation.

1. `/oauth2/login` is where ADFS is supposed to redirect you to after authenticating. Hence it should be the redirect URI you configure in ADFS. See also [this part of the config guide](http://django-auth-adfs.readthedocs.io/en/latest/adfs_config_guide.html#step-3-add-an-adfs-client). Documentation is indeed lacking some pointer as to **how** to start the authentication flow. [There's a middleware for it](http://django-auth-adfs.readthedocs.io/en/latest/extras.html#middleware), a function to build the URL](https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/util.py) and a template context processor(http://django-auth-adfs.readthedocs.io/en/latest/extras.html#context-processor) but after my restructuring of the documentation is became a bit of a hidden feature. 

1. Besides that, it might be a nice feature if there was some sort of `/oauth2/initiate` URL. Which also triggers the redirect to ADFS.

Hope this gets you going :)

**Comment by john-michael-murphy** [comment]
Joris, 

This fixed everything! You saved us. Thank you so much!!!

**Comment by jobec** [comment]
You're welcome.

Feel free to give feedback if you're missing some functionality. Or when something seems awkward.
