### ISSUE TITLE
GET /oauth2/login?code=xxxx 401, login failed. Now what?

### ISSUE THREAD

**Issue by jdmills-edu** [jobec/django-auth-adfs#23]
The middleware is redirecting me to ADFS. I authenticate, and get sent back to my redirect URI with a `?code=xxxxxxx `appended. Then... nothing. I just get a Login Failed message. Looking at the source I suppose this is coming from the authentication flow in django-auth-adfs views.py. Because `user = authenticate(authorization_code=code)` returns None (verified by tweaking views.py to print user to the console), a 401 is returned with the Login Failed error message.

I guess I don't really understand what's supposed to happen at this point. There aren't any users in my auth_user table, but I was under the impression django-auth-adfs would create them on the fly.

I also seem to remember seeing claims being printed out in the server console in earlier tests... now I don't even see those coming across.

What could be the missing link?

**Comment by jobec** [comment]
Could you enable debug logging an put the output in a gist or so? Along with the relevant parts of `settings.py`. That'll help in troubleshooting where it goes wrong.

Enabling debug is documented here: http://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html

**Comment by jdmills-edu** [comment]
Figured it out. This crucial bit was missing from settings.py.

`AUTHENTICATION_BACKENDS = (
    'django_auth_adfs.backend.AdfsBackend',
)`

Prior to inserting that, I didn't get anything useful out of debug. All I saw was the 401, Login Failed, and the code being sent in query parameters to /oauth2/login. After adding the authentication backend bit, debug helped me spot an invalid issuer setting. Fixed it, and everything is working fabulously.

I was so caught up in double and triple checking [these settings](http://django-auth-adfs.readthedocs.io/en/latest/adfs_config_guide.html) that I forgot to verify the fundamental installation requirements.

**Comment by jobec** [comment]
😄 That is indeed a rather important setting.
Glad you got it working.

Do you think there are things missing in the documentation that could have helped you in resolving the issue?

**Comment by jdmills-edu** [comment]
Mostly tunnel vision on my part. But I think one thing that tripped me up was this line [on the ADFS Configuration page](http://django-auth-adfs.readthedocs.io/en/latest/adfs_config_guide.html):

> If you followed this guide, you should end up with a configuration like this.

```
AUTH_ADFS = {
    "SERVER": "adfs.example.com",
    "CLIENT_ID": "django_website.adfs.client_id",
    "RESOURCE": "django_website.adfs.identifier",
    "AUDIENCE": "microsoft:identityserver:django_website.adfs.identifier",
    "ISSUER": "http://adfs.example.com/adfs/services/trust",
    "CA_BUNDLE": False,
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
    "USERNAME_CLAIM": "winaccountname",
    "GROUP_CLAIM": "group"
    "REDIR_URI": "http://webserver.example.com/oauth2/login",
}
```

That had me thinking, oh, if all those settings are correct, what else could possibly be wrong? Something like "if you've verified these settings are are still encountering problems, 1) enable debugging, and 2) verify that all of the configuration items in the [Installation Guide](http://django-auth-adfs.readthedocs.io/en/latest/install.html) are present and properly configured" would have been helpful.

But it's still embarrassing on my part :)

Quick question that's probably a separate issue: if I wanted to send additional claims (e.g. employee number, department, title, that sort of thing) and affiliate them with the Django auth user that your package creates and authenticates, how would you recommend that I go about doing that? I've seen several guides for extending the vanilla Django auth user model, but what would be the best way to streamline the process with django_auth_adfs?

**Comment by jobec** [comment]
I'll see what I can do to expand documentation for this.

**Comment by jobec** [comment]
It's been added, sort of, to a new FAQ section of the docs.

https://django-auth-adfs.readthedocs.io/en/latest/faq.html
