### ISSUE TITLE
AdfsBackend.authenticate() not called...

### ISSUE THREAD

**Issue by jedie** [jobec/django-auth-adfs#25]
I have a problem with django-auth-adfs: Login always failed.

I can see that `django_auth_adfs.backend.AdfsBackend.authenticate()` will be never called.

The signature of this method is `authenticate(self, authorization_code=None)` and `django.contrib.auth.authenticate()` will skip the call because of:

```
try:
    inspect.getcallargs(backend.authenticate, **credentials)
except TypeError:
    # This backend doesn't accept these credentials as arguments. Try the next one.
    continue
```
TypeError will be raised because `**credentials` dict has `username` and `password` arguments...

So i think there is a missing part somewhere ?!?

Any hints?

**Comment by jobec** [comment]
What’s your Django version?  

How do you try to login? Using a form with username and password? Or by redirecting a user to ADFS? The only way of logging in by having ADFS authenticate you and redirect you back to Django. More specifically, to the page like described at the bottom of this page: http://django-auth-adfs.readthedocs.io/en/latest/install.html

**Comment by jedie** [comment]
Hm, ok. Sorry i'm new to the AD stuff...

So I have to change the normal username/password login view to a redirect to the AD server?
A alternative login view that redirect to AD is still missing in django-auth-adfs, isn't it?
> the bottom of this page: http://django-auth-adfs.readthedocs.io/en/latest/install.html

There is not really information about how to get this worked. Where can i find more information about this?

**Comment by jobec** [comment]
this is now part of the alpha version 1.0.0 in the `v1-rewrite` branch, there's an example Django project showing how to do this:
https://github.com/jobec/django-auth-adfs/blob/fa8dc758d8acfd0406b76fb433a968566f87574a/example/adfs/templates/base.html#L29

Make sure to test drive the alpha version of v1.0.0. You should be able to install it like this
```
pip install git+https://github.com/jobec/django-auth-adfs.git@v1-rewrite
```

**Comment by jobec** [comment]
1.0.0rc1 was released with this in it.

https://pypi.org/project/django-auth-adfs/1.0.0rc1/

**Comment by alejandroleonbauzo** [comment]
Very much appreciated.
