### ISSUE TITLE
More example ADFS config is needed

### ISSUE THREAD

**Issue by jobec** [jobec/django-auth-adfs#3]
Some screenshots and sample config from the ADFS site should be included in the documentation.

**Comment by jobec** [comment]
Maybe also include a mentioning of [Get-ADFSClaimDescription](https://technet.microsoft.com/en-us/library/ee892361.aspx) for the ADFS claim name to token claim name mapping.

**Comment by patrikbi** [comment]
Unable to set CA_bundle to False.
Can't get it to connect:
requests.packages.urllib3.connection.VerifiedHTTPSConnection 

Some more samples would be great.

**Comment by jobec** [comment]
Could you open a separate issue for this?

Also, I would need more details about the error you get (a traceback for example) and more details about your exact config.

**Comment by dawiehyman** [comment]
very excited about your lib. Installed, but have no clue how to wire it up to my django application.  More specific usage samples  is needed.

**Comment by jobec** [comment]
Have a look in #11 
There you can find some recent troubleshooting with @patrikbi 
If you cannot get it to work that way, please open a separate issue and I'll try to help.

I'm also planning to review all documentation stuff, but haven't gotten to it yet.

**Comment by jobec** [comment]
Fixed in 5d9d162f5f50f35d510fa3b2b68a0f27601ab14b
