### ISSUE TITLE
/accounts/login/?next=/my/view

### ISSUE THREAD

**Issue by alejandroleonbauzo** [jobec/django-auth-adfs#30]
Hi, 

I configured my settings file and ADFS as per [the guide](http://django-auth-adfs.readthedocs.io/en/latest/adfs_config_guide.html).  Now my problem is that I don't see any errors in the console or at the server in the Event Viewer.  The only behavior I'm getting from visiting a @login_required view is automatic redirection to http://127.0.0.1:8000/accounts/login?next=/my/view  

What pointers could you give me to see what I am missing in my configuration to allow users authenticate in my ADFS and then being redirected to the @login_required view?

Thanks

**Comment by jobec** [comment]
What does your django config look like?

does it match to the settings described in http://django-auth-adfs.readthedocs.io/en/latest/install.html#setting-up-django ?

**Comment by alejandroleonbauzo** [comment]
Jobec I am going to close this issue because I no longer have it.  But I still don't have successful link between Django and AD FS, so will appreciate your insight.
