### ISSUE TITLE
MSIS9321: Received invalid OAuth request. 

### ISSUE THREAD

**Issue by alejandroleonbauzo** [jobec/django-auth-adfs#31]
I am using a Windows Server 2016 virtual machine to test the integration and I have successfully tested that the ADFS works via https://[MY-ADFDS]/adfs/ls/IdpInitiatedSignon.aspx signon test page. This is a portion that pertains to Django-ADFS in my settings.py file:

`AUTH_ADFS = {`
`"SERVER": "[MY-ADFS]",`
`"CLIENT_ID": "django_website.adfs.client_id",`
`"RESOURCE": "django_website.adfs.identifier",`
`"AUDIENCE": "microsoft:identityserver:django_website.adfs.identifier",`
`"ISSUER": "http://[MY-ADFS]/adfs/services/trust",`
`"CA_BUNDLE": False,`
`"CLAIM_MAPPING": {"first_name": "given_name",`
`"last_name": "family_name",`
`"email": "email"},`
`"USERNAME_CLAIM": "winaccountname",`
`"GROUP_CLAIM": "group",`
`"REDIR_URI": "http://[MY-DJANGO-APP]/oauth2/login",`
`}`

But still I am getting the following error:

> Description:
> Encountered error during federation passive request.
> 
> Additional Data
> 
> Protocol Name:
> OAuthAuthorizationProtocol
> 
> Relying Party:
> django_website.adfs.identifier
> 
> Exception details:
> Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthUnauthorizedClientException: MSIS9321: Received invalid OAuth request. The client 'django_website.adfs.client_id' is forbidden to access the resource 'django_website.adfs.identifier'.
> at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthProtocolContext.ValidateScopes(String scopeParameter, String clientId, String relyingPartyId)
> at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthAuthorization.OAuthAuthorizationRequestContext.ValidateCore()
> at Microsoft.IdentityServer.Web.Protocols.ProtocolContext.Validate()
> at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthAuthorization.OAuthAuthorizationProtocolHandler.GetRequiredPipelineBehaviors(ProtocolContext pContext)
> at Microsoft.IdentityServer.Web.PassiveProtocolListener.EvaluateHomeRealm(PassiveProtocolHandler protocolHandler, ProtocolContext protocolContext)
> at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)
> 

It makes no sense to my since, I ensured that the **Relying Party Trust** has the **Permit everyone** attribute.

Do you have any suggestions?

**Comment by alejandroleonbauzo** [comment]
I am using a Windows Server 2016 virtual machine to test the integration and I have successfully tested that the ADFS works via https://[MY-ADFDS]/adfs/ls/IdpInitiatedSignon.aspx signon test page.  This is a portion that pertains to Django-ADFS in my settings.py file:

`AUTH_ADFS = {
    "SERVER": "[MY-ADFS]",
    "CLIENT_ID": "django_website.adfs.client_id",
    "RESOURCE": "django_website.adfs.identifier",
    "AUDIENCE": "microsoft:identityserver:django_website.adfs.identifier",
    "ISSUER": "http://[MY-ADFS]/adfs/services/trust",
    "CA_BUNDLE": False,
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
    "USERNAME_CLAIM": "winaccountname",
    "GROUP_CLAIM": "group",
    "REDIR_URI": "http://[MY-DJANGO-APP]/oauth2/login",
}`

But still I am getting the following error: 

> Description:
> Encountered error during federation passive request. 
> 
> Additional Data 
> 
> Protocol Name: 
> OAuthAuthorizationProtocol 
> 
> Relying Party: 
> django_website.adfs.identifier 
> 
> Exception details: 
> Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthUnauthorizedClientException: MSIS9321: Received invalid OAuth request. The client 'django_website.adfs.client_id' is forbidden to access the resource 'django_website.adfs.identifier'.
>    at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthProtocolContext.ValidateScopes(String scopeParameter, String clientId, String relyingPartyId)
>    at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthAuthorization.OAuthAuthorizationRequestContext.ValidateCore()
>    at Microsoft.IdentityServer.Web.Protocols.ProtocolContext.Validate()
>    at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthAuthorization.OAuthAuthorizationProtocolHandler.GetRequiredPipelineBehaviors(ProtocolContext pContext)
>    at Microsoft.IdentityServer.Web.PassiveProtocolListener.EvaluateHomeRealm(PassiveProtocolHandler protocolHandler, ProtocolContext protocolContext)
>    at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)

**Comment by alejandroleonbauzo** [comment]
I used the Relying Party Trust.  I'm starting to think that the 'old way'
is the problem...

**Comment by alejandroleonbauzo** [comment]
So I Just created the **Application Groups** config on the AD FS 2016 and was able to see (at last!) the login (user password) page from AD FS thru the django adfs package.  Only thing is blocking me right now is that the Secret Key is not being sent over to AD FS and that blocks my user password login at the server.

What can I do to provide this setting in the configs?

**Comment by jobec** [comment]
What kind of config did you make? Because in the authorization code grant, a secret key is not needed. Maybe if you just remove it?

**Comment by alejandroleonbauzo** [comment]
How can I send you the steps I followed with images to config AD FS?

Here is my current Django config:

AUTH_ADFS = {
    "SERVER": "[ADFS-Server]",
    "CLIENT_ID": "6af7e5e6-a556-4350-b6ca-6d46d8569c07",
    "RESOURCE": "http://[DJANGO-APP]",
    "AUDIENCE": "http://[DJANGO-APP]",
    "ISSUER": "http://[ADFS-Server]/adfs/services/trust",
    "CA_BUNDLE": False,
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
    "USERNAME_CLAIM": "winaccountname",
    "GROUP_CLAIM": "group",
    "REDIR_URI": "http://[DJANGO-APP]/oauth2/login",
}

But as you can see there is no Secret Key value pair available in the config, I think this is the only missing part for me to work?

**Comment by jobec** [comment]
Did you configure it as a native application? Looks like that should do the trick.

I didn't have the chance yet to try it with server 2016 but I'll try to setup a lab with 2016 soon.
If you want you can mail me your steps. You should be able to extract my address from the commits.

**Comment by alejandroleonbauzo** [comment]
I went for OpenId Hybrid and then configure it as it was a Sererver Application.  Pretty much follow this step by step.  https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-openid-connect-with-ad-fs

When I find your email I will send you the steps that I took.

BTW, I will try and configure for Native Application and see if that does the trick.  Will let you know thanks...

**Comment by alejandroleonbauzo** [comment]
Ok so I configured it as Native Application and Django is getting an awful error here is the debug: 


DEBUG 2018-04-24 08:34:58,207 django_auth_adfs.backend Authorization code received. Fetching access token.
DEBUG 2018-04-24 08:34:58,207 django_auth_adfs.backend Authorization code received. Fetching access token.
DEBUG 2018-04-24 08:34:58,208 django_auth_adfs.backend :: token URL: https://win2016-edw.leon.local/adfs/oauth2/token
DEBUG 2018-04-24 08:34:58,208 django_auth_adfs.backend :: token URL: https://win2016-edw.leon.local/adfs/oauth2/token
DEBUG 2018-04-24 08:34:58,209 django_auth_adfs.backend :: authorization code: EwPduFL7NUSX-XO2IjLdbg.21y9K-ip1QgEAITLfIEzLCr
5r2k.Jj9PcY34ep6FKJY3xMOtYoAI1v00C6Aqwp5IDLG4sXtA86Dgbhgs2iopGm-a38Q9B0J2IGztH9gB-Tb4eDTq1moiv9ZjfiXNsANX91KPbYvjUne_do044Bf
PX4YK3nnityvP2GqjOlTJOxRrKxpEiAs40LiIe9vFCM8vA-lLwZy86jKEtu1DOdJmyGej6RFy2EkPjdr6a-lvRHlJrkUjHyfNLhQb8bgzwioVmKzU714HE2iS8U_
e9SHk68-luee-39Cqba47mqBDNW3HM6PmceD6JMa5ra4bXAKR_KNTzRy-OUOfilwy_1XhkPSszkFkai6aM8le7BPsBvPTxhLSXg
DEBUG 2018-04-24 08:34:58,209 django_auth_adfs.backend :: authorization code: EwPduFL7NUSX-XO2IjLdbg.21y9K-ip1QgEAITLfIEzLCr
5r2k.Jj9PcY34ep6FKJY3xMOtYoAI1v00C6Aqwp5IDLG4sXtA86Dgbhgs2iopGm-a38Q9B0J2IGztH9gB-Tb4eDTq1moiv9ZjfiXNsANX91KPbYvjUne_do044Bf
PX4YK3nnityvP2GqjOlTJOxRrKxpEiAs40LiIe9vFCM8vA-lLwZy86jKEtu1DOdJmyGej6RFy2EkPjdr6a-lvRHlJrkUjHyfNLhQb8bgzwioVmKzU714HE2iS8U_
e9SHk68-luee-39Cqba47mqBDNW3HM6PmceD6JMa5ra4bXAKR_KNTzRy-OUOfilwy_1XhkPSszkFkai6aM8le7BPsBvPTxhLSXg
DEBUG 2018-04-24 08:34:58,213 urllib3.connectionpool Starting new HTTPS connection (1): win2016-edw.leon.local
DEBUG 2018-04-24 08:34:58,309 urllib3.connectionpool https://win2016-edw.leon.local:443 "POST /adfs/oauth2/token HTTP/1.1" 2
00 4587
DEBUG 2018-04-24 08:34:58,312 django_auth_adfs.backend Received access token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im
tMZlBWanJCMVk5eXVEeWxsd1B6TEFwZXRTTSJ9.eyJhdWQiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAiLCJpc3MiOiJodHRwOi8vd2luMjAxNi1lZHcubGVvbi5sb
2NhbC9hZGZzL3NlcnZpY2VzL3RydXN0IiwiaWF0IjoxNTI0NTc2ODk3LCJleHAiOjE1MjQ1ODA0OTcsImFwcHR5cGUiOiJQdWJsaWMiLCJhcHBpZCI6IjgwOTkwN
mY3LWJjYmMtNGVmNC1hZGFmLTYwMTljZjQwYmUzMiIsImF1dGhtZXRob2QiOiJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YWM6Y2xhc3NlczpQYXNzd29yZ
FByb3RlY3RlZFRyYW5zcG9ydCIsImF1dGhfdGltZSI6IjIwMTgtMDQtMjRUMTI6Mzg6NDAuNTIzWiIsInZlciI6IjEuMCJ9.Kx6OOXtWuRTsvTyj3MGoceWiPDOu
mFFOqMjdQ0frnRkxyVsihfevtgFA__VUPxdMBi7QMhFTmrqP0pIqPubIQvjNPXWMInBXlo88cSwQAlS2pnCx2ABt7kBKFBiF-qR-Fm6PQJiuTEJ1cA5FocXnGCcO
eOFJc5Xu-TlqYTbGYE-oj6ghXugHujH0ZbZRhxqYzAK1NB8IQZit_zXI9IDu2Qx3gX5JTyF8RJS4PCc_QID_-tM6uHruY0j4KZEC9hwjeoXG5QgZoDn4vjoFZ39T
Q99ou2AQ021gMQV8QuCt-0XY_jQUZBIrJNzRiy3ik3lZ4T-QjSXDX0_mN4qb2pMWYQ
DEBUG 2018-04-24 08:34:58,312 django_auth_adfs.backend Received access token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im
tMZlBWanJCMVk5eXVEeWxsd1B6TEFwZXRTTSJ9.eyJhdWQiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAiLCJpc3MiOiJodHRwOi8vd2luMjAxNi1lZHcubGVvbi5sb
2NhbC9hZGZzL3NlcnZpY2VzL3RydXN0IiwiaWF0IjoxNTI0NTc2ODk3LCJleHAiOjE1MjQ1ODA0OTcsImFwcHR5cGUiOiJQdWJsaWMiLCJhcHBpZCI6IjgwOTkwN
mY3LWJjYmMtNGVmNC1hZGFmLTYwMTljZjQwYmUzMiIsImF1dGhtZXRob2QiOiJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YWM6Y2xhc3NlczpQYXNzd29yZ
FByb3RlY3RlZFRyYW5zcG9ydCIsImF1dGhfdGltZSI6IjIwMTgtMDQtMjRUMTI6Mzg6NDAuNTIzWiIsInZlciI6IjEuMCJ9.Kx6OOXtWuRTsvTyj3MGoceWiPDOu
mFFOqMjdQ0frnRkxyVsihfevtgFA__VUPxdMBi7QMhFTmrqP0pIqPubIQvjNPXWMInBXlo88cSwQAlS2pnCx2ABt7kBKFBiF-qR-Fm6PQJiuTEJ1cA5FocXnGCcO
eOFJc5Xu-TlqYTbGYE-oj6ghXugHujH0ZbZRhxqYzAK1NB8IQZit_zXI9IDu2Qx3gX5JTyF8RJS4PCc_QID_-tM6uHruY0j4KZEC9hwjeoXG5QgZoDn4vjoFZ39T
Q99ou2AQ021gMQV8QuCt-0XY_jQUZBIrJNzRiy3ik3lZ4T-QjSXDX0_mN4qb2pMWYQ
DEBUG 2018-04-24 08:34:58,319 django_auth_adfs.backend JWT payload:
{'appid': '809906f7-bcbc-4ef4-adaf-6019cf40be32',
 'apptype': 'Public',
 'aud': 'http://127.0.0.1:8000',
 'auth_time': '2018-04-24T12:38:40.523Z',
 'authmethod': 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport',
 'exp': 1524580497,
 'iat': 1524576897,
 'iss': 'http://win2016-edw.leon.local/adfs/services/trust',
 'ver': '1.0'}
DEBUG 2018-04-24 08:34:58,319 django_auth_adfs.backend JWT payload:
{'appid': '809906f7-bcbc-4ef4-adaf-6019cf40be32',
 'apptype': 'Public',
 'aud': 'http://127.0.0.1:8000',
 'auth_time': '2018-04-24T12:38:40.523Z',
 'authmethod': 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport',
 'exp': 1524580497,
 'iat': 1524576897,
 'iss': 'http://win2016-edw.leon.local/adfs/services/trust',
 'ver': '1.0'}
ERROR 2018-04-24 08:34:58,333 django.request Internal Server Error: /oauth2/login

**Comment by alejandroleonbauzo** [comment]
It looks like the winaccountname in the config is causing the problem?

AUTH_ADFS = {
    "SERVER": "[ADFS-SERVER]",
    "CLIENT_ID": "809906f7-bcbc-4ef4-adaf-6019cf40be32",
    "RESOURCE": "http://127.0.0.1:8000",
    "AUDIENCE": "http://127.0.0.1:8000",
    "ISSUER": "http://[ADFS-SERVER]/adfs/services/trust",
    "CA_BUNDLE": False,
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
    "USERNAME_CLAIM": "winaccountname",
    "GROUP_CLAIM": "group",
    "REDIR_URI": "http://127.0.0.1:8000/oauth2/login",
}

**Comment by jobec** [comment]
You did not configure any claims. 

```
DEBUG 2018-04-24 08:34:58,319 django_auth_adfs.backend JWT payload:
{'appid': '809906f7-bcbc-4ef4-adaf-6019cf40be32',
 'apptype': 'Public',
 'aud': 'http://127.0.0.1:8000',
 'auth_time': '2018-04-24T12:38:40.523Z',
 'authmethod': 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport',
 'exp': 1524580497,
 'iat': 1524576897,
 'iss': 'http://[ADFS-SERVER]/adfs/services/trust',
 'ver': '1.0'}
```
This is what is in the ADFS access token. As you see, there are no claims at all.

**Comment by alejandroleonbauzo** [comment]
Ok what a total noob I am thanks for clarifying!

**Comment by alejandroleonbauzo** [comment]
Will close the Issue since the original problem was resolved using new authentication paradigm of Application Groups in AD FS 2016.  I still have problem with claim mapping which will try to work on later on.  If not successful will open different issue.  Thanks.

**Comment by alejandroleonbauzo** [comment]
I will reopen issue to propose to add an optional section of quick step by step config of AD FS in 2016.

**Comment by jobec** [comment]
Screenshots like those for 2016 are more then welcome.

**Comment by alejandroleonbauzo** [comment]
Will attach them soon.  Thanks.

**Comment by alejandroleonbauzo** [comment]
# Windows 2016 Configuration

Open **AD FS Manager** and click on **Application Groups**
![image](https://user-images.githubusercontent.com/37311230/39205608-c6801584-47c0-11e8-8d91-e088e0c0c48b.png)

Click on **Add Application Group...**
![image](https://user-images.githubusercontent.com/37311230/39205681-fb876962-47c0-11e8-9941-2c1c139f1e1f.png)

Fill in the **Application Group** Information & select **Native application**, click _Next_:
![image](https://user-images.githubusercontent.com/37311230/39205713-148fb7fc-47c1-11e8-892f-dcd03e986bfc.png)

Add the Redirect URI (http://127.0.0.1:8000/oauth2/login) and take note of the Client Identifier
![image](https://user-images.githubusercontent.com/37311230/39205789-4f2e2fd8-47c1-11e8-9bcc-4d9a4f389f14.png)

Click Next.
![image](https://user-images.githubusercontent.com/37311230/39205814-63f273d4-47c1-11e8-8387-9b976f22b08a.png)

Confirm window
![image](https://user-images.githubusercontent.com/37311230/39205830-7049e36a-47c1-11e8-95bd-7273b92c7a25.png)

Now the **Application Group** should be populated with the one we just created.
![image](https://user-images.githubusercontent.com/37311230/39205861-846f9cea-47c1-11e8-99de-adb76ad61061.png)


Double click on the new **Application Group** (_Django Application Group_)
![image](https://user-images.githubusercontent.com/37311230/39205902-a10bfcea-47c1-11e8-9f0e-8ec22ffc2663.png)


Click on **Add application** and select **Web API**, click Next
![image](https://user-images.githubusercontent.com/37311230/39205948-b408452e-47c1-11e8-8a5c-35d212e5b92a.png)


Enter and Add the URL of your Django app, then click Next
![image](https://user-images.githubusercontent.com/37311230/39206106-23b2df7e-47c2-11e8-9266-763711af4e74.png)

Make sure **Permit everyone** is selected, click Next
![image](https://user-images.githubusercontent.com/37311230/39206159-3e6641e4-47c2-11e8-80e8-e0c71a8bbda4.png)

Confirm that openid is checked, click Next
![image](https://user-images.githubusercontent.com/37311230/39206184-50e87dc8-47c2-11e8-8528-df716ae7e7bb.png)


Review the configuration of the new Web API, click Next
![image](https://user-images.githubusercontent.com/37311230/39206218-68c26e4a-47c2-11e8-8230-1fc2f8090b2d.png)

Click Close
![image](https://user-images.githubusercontent.com/37311230/39206233-751bb034-47c2-11e8-83c4-40eef45ac425.png)

Now the configuration on AD FS 2016 should look like this
![image](https://user-images.githubusercontent.com/37311230/39206249-82733cb6-47c2-11e8-91fb-50baedb519f7.png)

Ok , we are not done.  Claims need to be configured!

Click on **Edit** over the **Web API**
![image](https://user-images.githubusercontent.com/37311230/39206301-a537749c-47c2-11e8-80ca-77ddba6b148f.png)

Go to the tab **Issuance Transform Rules** 
![image](https://user-images.githubusercontent.com/37311230/39206328-b5368aea-47c2-11e8-9848-519b4b1950e0.png)

Click on the button **Add Rule**
![image](https://user-images.githubusercontent.com/37311230/39206357-c9a8ccf4-47c2-11e8-8691-cf03d020e753.png)

Click Next on that first screen confirming that **Send LDAP Attributes as Claims** is selected
![image](https://user-images.githubusercontent.com/37311230/39206385-e0d1739a-47c2-11e8-83f0-5e586450e229.png)

Now we pretty much mimic the Claim configuration of [the configuration Guide](http://django-auth-adfs.readthedocs.io/en/latest/adfs_config_guide.html#step-2-configuring-claims)
![image](https://user-images.githubusercontent.com/37311230/39206500-34ed5a20-47c3-11e8-896a-c7b129fdc0b6.png)

Click OK 
![image](https://user-images.githubusercontent.com/37311230/39206513-3e1aa670-47c3-11e8-827f-2aa4cba52d77.png)

Click OK again
![image](https://user-images.githubusercontent.com/37311230/39206532-4a7fa096-47c3-11e8-9684-507fa7120cca.png)


Now you are done at AD FS, Django ADFS config now should look some-what like this:

`AUTH_ADFS = {`
`    "SERVER": "[YOUR-ADFS-SERVER",`
`    "CLIENT_ID": "abe63356-4563-4489-a937-6906b83ce1e6",`  # <-- Client Identifier earlier!
`    "RESOURCE": "http://127.0.0.1:8000",`  # <--- Web API Identifier
`    "AUDIENCE": "http://127.0.0.1:8000",`  # <--- Web API Identifier
`    "ISSUER": "http://win2016-edw.leon.local/adfs/services/trust",`
`    "CA_BUNDLE": False,`
`    "CLAIM_MAPPING": {"first_name": "given_name",`
`                      "last_name": "family_name",`
`                      "email": "email"},`
`    "USERNAME_CLAIM": "winaccountname",`
`    "GROUP_CLAIM": "group",`
`    "REDIR_URI": "http://127.0.0.1:8000/oauth2/login",` 
`}`

**Comment by alejandroleonbauzo** [comment]
I just tested these steps and work.  Now how do I actually consume this claim values once authenticated by AD FS in Django?

**Comment by jobec** [comment]
The claim values get copied into the user's profile. That's what the settings `CLAIM_MAPPING`, `USERNAME_CLAIM`, `GROUP_CLAIM` and `BOOLEAN_CLAIM_MAPPING` are for.

Thanks for the screenshots. I'll try to get them into the documentation shortly. I'll also try to simulate it myself once, just to get some feeling with it.

**Comment by jobec** [comment]
Oh wait, you mean the ADFS side of things... Yes, that's bit more difficult. That feature was a contribution but I never really tried the ADFS config myself 😇 I'll figure it out and let you know.

**Comment by jobec** [comment]
1. In the claim editing window, add a claim and chose "Send Group Membership as a Claim".
1. Set a name and pick a group the user needs to be member of.
1. As the **Outgoing Claim type**, type something like `user_is_staff` and set the **Outgoing claim value** to `yes`
1. In the django settings for django-auth-adfs add a boolean claim mapping:

```python
AUTH_ADFS = {
    "BOOLEAN_CLAIM_MAPPING": {"is_staff": "user_is_staff"}
}
```

**Comment by alejandroleonbauzo** [comment]
It does not work I will open different issue tomorrow thanks for your help.  You can close this issue when you feel.

**Comment by jobec** [comment]
FYI: The code in branch `v1-rewrite` now allows to set boolean values based on group membership, instead of having to configure a separate claim for it.

Have a look here for the setting: https://github.com/jobec/django-auth-adfs/blob/v1-rewrite/docs/configuration.rst#group_flag_mapping

**Comment by alejandroleonbauzo** [comment]
Wao?

**Comment by jobec** [comment]
🙃 Didn't get that...

**Comment by alejandroleonbauzo** [comment]
That's awesome feature!

**Comment by alejandroleonbauzo** [comment]
Do we have ETA on this changes being merged into master and version Bumped for stable release?

**Comment by alejandroleonbauzo** [comment]
I think that is a good idea.  That way I can go forward with a release on my side.

**Comment by jobec** [comment]
1.0.0rc1 is released.

docs are here: https://django-auth-adfs.readthedocs.io/en/latest/faq.html

**Comment by jobec** [comment]
Docs are updated with an adfs 2016 config guide.
