### ISSUE TITLE
How groups are consumed in Django from the claim?

### ISSUE THREAD

**Issue by alejandroleonbauzo** [jobec/django-auth-adfs#32]
Having this settings file:

> AUTH_ADFS = {
>    ....
>     "CLAIM_MAPPING": {"first_name": "given_name",
>                       "last_name": "family_name",
>                       "email": "email"},
>     "USERNAME_CLAIM": "winaccountname",
>     "BOOLEAN_CLAIM_MAPPING": {"is_staff": "user_is_staff",
>                               "is_superuser": "user_is_superuser"},
>     "GROUP_CLAIM": "group",
>    ....
> }
> 

How the GROUP_CLAIM is consumed in Django side?

**Comment by jobec** [comment]
The `GROUP_CLAIM` setting should point to a claim name that contains the list of groups a user is member of.  
The groups in that claim are matched against groups in Django. If there is a match, the user is added to that group in Django.

So, the name of your groups in Django have to match those in active directory.

Documentation: http://django-auth-adfs.readthedocs.io/en/latest/configuration.html#group-claim

Code that does this: https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/backend.py#L253

**Comment by alejandroleonbauzo** [comment]
Thanks!
