### ISSUE TITLE
Provide Link to Logout for templates

### ISSUE THREAD

**Issue by alejandroleonbauzo** [jobec/django-auth-adfs#33]
Could we have a link to logout of AD FS at template level opposed to login? 

http://django-auth-adfs.readthedocs.io/en/latest/extras.html
```
 ...
 <a href="{{ ADFS_AUTH_URL }}">Click here to log in</a>
 ...

```

**Comment by alejandroleonbauzo** [comment]
Documentation of Microsoft on similar request: 
https://social.technet.microsoft.com/wiki/contents/articles/1439.ad-fs-how-to-invoke-a-ws-federation-sign-out.aspx

**Comment by alejandroleonbauzo** [comment]
So I have looked around and the link can be pointed to https://[ADFSURL]/adfs/ls/?wa=wsignout1.0

**Comment by alejandroleonbauzo** [comment]
this also needs to clear the session on Django side

**Comment by alejandroleonbauzo** [comment]
> def get_adfs_auth_url_logout():
>     """
>     This function returns the ADFS authorization URL.
> 
>     Returns:
>         str: The redirect URI
> 
>     """
>     return "https://{0}/adfs/ls/?wa=wsignout1.0'.format(settings.SERVER)
>

**Comment by alejandroleonbauzo** [comment]
```
from django_auth_adfs.util import get_adfs_auth_url


def adfs_url(request):
    """
    This context processor function makes the ADFS authorization URL
    available as a Django template variable.

    Args:
        request (django.http.request.HttpRequest): A Django Request object

    Returns:
        dict: A dictionary with the ADFS authorization URL
    """

    return {"ADFS_AUTH_URL": get_adfs_auth_url(),
                "ADFS_AUTH_URL_LOGOUT": get_adfs_auth_url_logout(),}

```

**Comment by jobec** [comment]
👍 
I'm busy with rewriting this module and a way to perform a logout will be included.

**Comment by alejandroleonbauzo** [comment]
Very much obliged

**Comment by jobec** [comment]
In the `v1-rewrite` branch, there's an example Django project showing how to get this working.

https://github.com/jobec/django-auth-adfs/blob/fa8dc758d8acfd0406b76fb433a968566f87574a/example/adfs/templates/base.html#L27

Make sure to test drive the alpha version of v1.0.0. You should be able to install it like this
```
pip install git+https://github.com/jobec/django-auth-adfs.git@v1-rewrite
```

**Comment by alejandroleonbauzo** [comment]
Sure will let you know thanks

**Comment by alejandroleonbauzo** [comment]
As instructed I installed the alpha version. 

After that I tried to run the project and the feature gave me an error:

>   File "D:\x\y\z\project\venv\lib\site-packages\django\urls\resolvers.py", line 632
> , in _reverse_with_prefix
>     raise NoReverseMatch(msg)
> django.urls.exceptions.NoReverseMatch: Reverse for 'logout' not found. 'logout' is not a valid view function o
> r pattern name.
> HTTP 500 - Server Error, check the rest of the log
>                    for details
> [2018-05-31 09:06:26,995] views: WARNING - HTTP 500 - Server Error, check the rest of the log
>                    for details

**Comment by jobec** [comment]
What does your `url.py` look like?

Make sure it contains this:
```
urlpatterns = [
    path('oauth2/', include('django_auth_adfs.urls')),
]
```
See [this as an example](https://github.com/jobec/django-auth-adfs/blob/v1-rewrite/example/adfs/mysite/urls.py) for `url.py`

See [this as an example](https://github.com/jobec/django-auth-adfs/blob/v1-rewrite/example/adfs/templates/base.html#L27) for a logout link

**Comment by alejandroleonbauzo** [comment]
still giving me same error cannot reverse to logout.  Do I have to uninstall regular django-auth-adfs and reinstall alpha?

**Comment by alejandroleonbauzo** [comment]
Yes that seems to be the problem for this part.  Had to 

`pip uninstall django-auth-adfs`

and then do:

`pip install git+https://github.com/jobec/django-auth-adfs.git@v1-rewrite`


Now.  I am getting another error:

> AttributeError: 'Settings' object has no attribute 'LOOUT_URL'

What I am missing here?

**Comment by jobec** [comment]
There's no such setting as LOGOUT_URL. if you delete it, it should work.

You'll be redirected to ADFS for the logout. That URL is calculated and there's no setting for that.

**Comment by alejandroleonbauzo** [comment]
It says LOOUT misspelled, maybe that is the problem

**Comment by alejandroleonbauzo** [comment]
Let me know when to test again!

**Comment by jobec** [comment]
Weird... I missed your response of 4 days ago...

Anyway, it was indeed a bug (limited to using the login required middleware). It's fixed now. You may test again.

**Comment by alejandroleonbauzo** [comment]
Now I reinstall the re-write version, ran the server but without the logout tag, and I am getting the following error:

ModuleNotFoundError at /X/Y/Z/
No module named 'django_auth_adfs.context_processors'

**Comment by jobec** [comment]
Indeed, the context processor for providing those login/logout links is deprecated in favour of the normal Django url handling.

**Comment by alejandroleonbauzo** [comment]
Ok So now I remove the entry in settings.py.  The web app works now.  I did logged out successfully one last thing....  

With the required login middleware if I am signed off/logged out it will redirect me to the following route http://127.0.0.1:8000/accounts/login/ in which case I am receiving an 404 error.  It should point back to the login page of ADFS.

**Comment by jobec** [comment]
You're right. It doesn't implement the "next" parameter yet.

If you don't use the login middleware, but instead use the loginrequired mixin/decorator on a view, it works. [See here for an example](https://github.com/jobec/django-auth-adfs/blob/31562b75fee2c7feb8605c280ff1362e83ee32a9/example/adfs/polls/views.py#L36)

I'll try to implement the same behaviour for the login required middleware.

**Comment by alejandroleonbauzo** [comment]
I will really appreciate your efforts towards this feature, since I am working an Intranet app.

**Comment by jobec** [comment]
The `v1-rewrite` branch now supports the `next` parameter.

Can you have another go at it an let me know?

I'm guessing the rewrite of the code is almost finished. Except for overhauling the unit tests and some of the documentation.

**Comment by alejandroleonbauzo** [comment]
Sorry for late response I've been sick.  The logout will append the next parameter but the loging required middleware is not kicking in (redirect to ADFS login) when landing back on the app.  It just show the 403 error.

**Comment by jobec** [comment]
Are you sure you used the latest version from `v1-rewrite` ?

This sets the `next` query param
https://github.com/jobec/django-auth-adfs/blob/3a101b3509b3648e072ca103c56b61a1ec1420a6/django_auth_adfs/middleware.py#L58 and redirect to this view:
https://github.com/jobec/django-auth-adfs/blob/3a101b3509b3648e072ca103c56b61a1ec1420a6/django_auth_adfs/views.py#L63 Which then builds the URL towards ADFS including the state param:
https://github.com/jobec/django-auth-adfs/blob/3a101b3509b3648e072ca103c56b61a1ec1420a6/django_auth_adfs/config.py#L227-L239 During redirect back from ADFS, the state is again used to do the final redirect back to the page that triggered the login.
https://github.com/jobec/django-auth-adfs/blob/3a101b3509b3648e072ca103c56b61a1ec1420a6/django_auth_adfs/views.py#L22-L42

**Comment by alejandroleonbauzo** [comment]
Yes I uninstalled and install again the latest version with the same result.  

I think the problem is that the URL **http://127.0.0.1:8000/accounts/login/?next=/** is not being captured by the package for some reason thus falling thru the last url parameter redirecting to my view and then the validation gets triggered for user.is_authenticated throwing 403 error.

Here are my settings:

> urls.py

    path('oauth2/', include('django_auth_adfs.urls')),

> settings.py 

   INSTALLED_APPS = [
        ...
       'django_auth_adfs',
    ]

    MIDDLEWARE = [ 
        ...
        'django_auth_adfs.middleware.LoginRequiredMiddleware', 
    ]

    AUTH_ADFS = {
        "SERVER": os.getenv('AUTH_ADFS_SERVER'),
        "CLIENT_ID": os.getenv('AUTH_ADFS_CLIENT_ID'),
        "RESOURCE": os.getenv('AUTH_ADFS_RESOURCE'),
        "AUDIENCE": os.getenv('AUTH_ADFS_AUDIENCE'),
        "ISSUER": os.getenv('AUTH_ADFS_ISSUER'),
        "CA_BUNDLE": False,
        "CLAIM_MAPPING": {
            "email": "email",
            "first_name": "given_name",
            "last_name": "family_name",
            "department": "Department",
            "company_code": "Company",
        },
        "USERNAME_CLAIM": "winaccountname",
        "GROUP_CLAIM": "group",
        "GROUP_FLAG_MAPPING": {
            "is_staff": "Django Admins",
            "is_superuser": "Django Admins"
        },
        "REDIR_URI": os.getenv('AUTH_ADFS_REDIR_URI'),
    }

**Comment by jobec** [comment]
did you set this in `settings.py`
```
LOGIN_URL = "django_auth_adfs:login"
```
Right now, the `LoginRequiredMiddleware` redirect to whatever `LOGIN_URL` is set to, mimicing what the standard Django `LoginRequired` mixin/decorator does.

If it works by setting `LOGIN_URL`, then I'll have to see whether the middleware shoudn't do so by default 🤔 .

**Comment by jobec** [comment]
With that set, I get this flow when using the included example project:
![image](https://user-images.githubusercontent.com/16192496/41315083-d5891932-6e8e-11e8-9264-565c2dac57e8.png)

**Comment by alejandroleonbauzo** [comment]
No I have not set it, but I will now and fire up another test.  Will let you know.

**Comment by alejandroleonbauzo** [comment]
That setting seems to work but now on ADFS I am getting another error: 

	Exception details: 
	Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthInvalidClientRedirectUriException: MSIS9224: Received invalid OAuth authorization request. The received 'redirect_uri' parameter is not a valid registered redirect URI for the client identifier: 'f9a487be-ae3a-47f5-b91f-2cad4e2f3f5a'. Received redirect_uri: 'http://127.0.0.1:8000/oauth2/callback'. 
		at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthProtocolContext.ValidateClientRedirectURI(OAuthClient client, String clientID, String redirectURI)
		at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthAuthorization.OAuthAuthorizationRequestContext.ValidateCore()
		at Microsoft.IdentityServer.Web.Protocols.ProtocolContext.Validate()
		at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthAuthorization.OAuthAuthorizationProtocolHandler.GetRequiredPipelineBehaviors(ProtocolContext pContext)
		at Microsoft.IdentityServer.Web.PassiveProtocolListener.EvaluateHomeRealm(PassiveProtocolHandler protocolHandler, ProtocolContext protocolContext)
		at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)


Perhaps another setting needs to be changed?

    AUTH_ADFS = [
        "REDIR_URI": "....."
    ]

**Comment by jobec** [comment]
The redirect uri is now calculated automatically.
It also moved to /oauth2/callback

So, in ADFS you’ll have to register http://127.0.0.1:8000/oauth2/callback
I know, that’s a change that breaks backwards compatibility...

**Comment by alejandroleonbauzo** [comment]
No problem!  I will change that setting in ADFS and fire other test, will let you know.

**Comment by alejandroleonbauzo** [comment]
Success!!!

**Comment by jobec** [comment]
Closing this as the original issue is fixed in the `v1-rewrite` branch.
