### ISSUE TITLE
How can I consume new claim field in user object for example "Department"?

### ISSUE THREAD

**Issue by alejandroleonbauzo** [jobec/django-auth-adfs#34]
How can I consume new claim field in user object for example "Department"?

> AUTH_ADFS = {
>  ...
>     "CLAIM_MAPPING": {"first_name": "given_name",
>                       "last_name": "family_name",
>                       "email": "email",
>                       **"department": "department"},**
>     "USERNAME_CLAIM": "winaccountname",
>     "BOOLEAN_CLAIM_MAPPING": {"is_staff": "user_is_staff",
>                               "is_superuser": "user_is_superuser"},
>     "GROUP_CLAIM": "group",
>  ...
> }
>

**Comment by jobec** [comment]
Have a look at #24 

I still have to properly document this.
