### ISSUE TITLE
calling AdfsBackend.authenticate()

### ISSUE THREAD

**Issue by prashant0493** [jobec/django-auth-adfs#36]
I am done with minimal configurations as exactly suggested by docs (http://django-auth-adfs.readthedocs.io/en/latest/configuration.html --> settings section). 
The middleware is redirecting me to ADFS. I authenticate, and get sent back to my REDIR_URL with a #code=xxxxxxx appended.  

Currently I have managed to capture this authentication code via AJAX call.

Once we receive a authorization code, there should be token validation end point on the client side (I assume that is resolved by CLIENT_ID in settings.py)
How should the subsequent flow be? I think that link is missing somewhere.

**Comment by jobec** [comment]
What are you trying to do exactly? Are you trying to use this module for a Single Page Application?

The redir URL set in ADFS should point to a specific URL and the redirect is not in the form of `#code=xxxx` but as a query parameters like so ``?code=xxxxx`. This query parameter is picked up by django-auth-adfs and then exchanged for an access token.

You shouldn't do anything client side, the scope of this module is logging in to Django and create a session for a user.

**Comment by prashant0493** [comment]
@jobec Thanks for quick response. I am using this module in a multi-page application. For my organization specific ADFS, REDIRECT happens in the form of #code=xxxx.  I will have to find a work around to convert in into ``?code=xxxxx`` somehow, may be I should introduce few JavaScript functions in between.

**Comment by prashant0493** [comment]
@jobec your comments on this are highly appreciated, thank you.

**Comment by jobec** [comment]
The difference between `#code=xxxx` and `?code=xxxx` is the OAuth2 flow that is chosen.

The one with `#` indicates the **implicit grant flow** is being used. This one is triggered by setting [`response_type=token`](https://tools.ietf.org/html/rfc6749#section-4.2.1) in the redirect to ADFS and is only supported on ADFS 4.0 on windows 2016.

The one django-auth-adfs is using is the **authorization code grant flow**, it's being triggered by setting [`response_type=code`](https://tools.ietf.org/html/rfc6749#section-4.1.1) in the redirect to ADFS. You can see it being set [here in the code](https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/util.py#L12)

As far as I know, there is no way to disable the authorization code grant flow, so it should work out of the box.

How are you directing your users to ADFS?
