### ISSUE TITLE
Why redirected to /accounts/profile/ after login?

### ISSUE THREAD

**Issue by alejandroleonbauzo** [jobec/django-auth-adfs#37]
Why I am always redirected to /accounts/profile/ after login?  Can this behavior be modified on config?

**Comment by jobec** [comment]
It's default Django behaviour.
And yes, you can change it by setting the the standard Django setting named [LOGIN_REDIRECT_URL](https://docs.djangoproject.com/en/2.0/ref/settings/#login-redirect-url)
