### ISSUE TITLE
401 Login Failed (Django) vs. An Access Token was successfully issued to client (ADFS)

### ISSUE THREAD

**Issue by alejandroleonbauzo** [jobec/django-auth-adfs#38]
Hi, 

I don't know what I did to mess things up but right now in my development environment I am getting code 401 Login Failed.  When I debug on the event viewer on ADFS it says that all good "An Access Token was successfully issued to client: blablabla"

I debug the package:

> class OAuth2View(View):
>     def get(self, request):
>         """
>         Handles the redirect from ADFS to our site.
>         We try to process the passed authorization code and login the user.
> 
>         Args:
>             request (django.http.request.HttpRequest): A Django Request object
>         """
>         code = request.GET.get("code", None)
> 
>         print("Code: {}".format(code))
> 
>         user = authenticate(authorization_code=code)
> 
>         print("user{}".format(user))
>         if user is not None:
>             if user.is_active:
>                 login(request, user)
>                 # Redirect to the "after login" page.
>                 # Because we got redirected from ADFS, we can't know where the
>                 # user came from.
>                 if settings.LOGIN_REDIRECT_URL:
>                     return redirect(settings.LOGIN_REDIRECT_URL)
>                 else:
>                     return redirect(django_settings.LOGIN_REDIRECT_URL)
>             else:
>                 # Return a 'disabled account' error message
>                 return HttpResponse("Account disabled", status=403)
>         else:
>             # Return an 'invalid login' error message
>             return HttpResponse("Login failed", status=401)

And I placed 2 print commands in the very begging of each variable assignation.  It turns out that the  **code** is getting populated by the ADFS response on the query string but the **user=authenticate** command its returning **None**.  

What could possibly be causing this behavior?

My settings:

> AUTH_ADFS = {
>     "SERVER": '[SERVER]',
>     "CLIENT_ID": 'f9a487be-ae3a-47f5-b91f-2cad4e2f3f5a',
>     "RESOURCE": 'http://127.0.0.1:8000',
>     "AUDIENCE": 'http://127.0.0.1:8000',
>     "ISSUER": 'http://[SERVER]/adfs/services/trust',
>     "CA_BUNDLE": False,
>     "CLAIM_MAPPING": {
>         "email": "email",
>         "first_name": "given_name",
>         "last_name": "family_name",
>     },
>     "USERNAME_CLAIM": "winaccountname",
>     "GROUP_CLAIM": "group",
>     "BOOLEAN_CLAIM_MAPPING": {
>         "is_staff": "user_is_staff",
>         "is_superuser": "user_is_superuser"
>     },
>     "REDIR_URI": 'http://127.0.0.1:8000/oauth2/login',
> }

**Comment by jobec** [comment]
What does the python console show you if you enable debugging and logging? See the troubleshooting section of the documentation.

**Comment by alejandroleonbauzo** [comment]
This is what I am getting back in the console:

> Code: EwPduFL7NUSX-XO2IjLdbg.6-GDEdbA1QgFAOb8ZZBspl-H-F4.pgwWHy7M97jGl5OjfbVihhkk9SpCvDcMpBtEVxeZzapNatKqMLC4l
> -GEkyzuX7vqEQwlfK8IRE8mnURsj0vMDYG2a8GU6O7azK7v-kwZ5XDjNO-sFto54VAFOLiY30gRctsva0DBzbjjT0-TuE_gPNWBv_SdyLwuFco
> 59-GnygJTLgHipQ-Adc76tEcKqN8i55lWrysv3JNrBT8QG3Watyr33wILDDHP5xSGAqzsOhmvqetUR8qRVv-4vtim9-sH0qyq_p5EvfeGDugRz
> 0h5hpDevyMVrWn7K0vKCADjCmYwI1eGUjA9Djn9_OYQ_acwm2s0MVUvlA4PIXb6P_JZMQ
> Retrieving ADFS metadata file from https://win2016-edw.leon.local/FederationMetadata/2007-06/FederationMetadat
> a.xml
> userNone
> [2018-05-23 12:53:20,133] log: WARNING - Unauthorized: /oauth2/login
> [23/May/2018 12:53:20] "GET /oauth2/login?code=EwPduFL7NUSX-XO2IjLdbg.6-GDEdbA1QgFAOb8ZZBspl-H-F4.pgwWHy7M97jG
> l5OjfbVihhkk9SpCvDcMpBtEVxeZzapNatKqMLC4l-GEkyzuX7vqEQwlfK8IRE8mnURsj0vMDYG2a8GU6O7azK7v-kwZ5XDjNO-sFto54VAFOL
> iY30gRctsva0DBzbjjT0-TuE_gPNWBv_SdyLwuFco59-GnygJTLgHipQ-Adc76tEcKqN8i55lWrysv3JNrBT8QG3Watyr33wILDDHP5xSGAqzs
> OhmvqetUR8qRVv-4vtim9-sH0qyq_p5EvfeGDugRz0h5hpDevyMVrWn7K0vKCADjCmYwI1eGUjA9Djn9_OYQ_acwm2s0MVUvlA4PIXb6P_JZMQ
>  HTTP/1.1" 401 12
> [23/May/2018 12:53:20] "GET /favicon.ico HTTP/1.1" 302 0
> Code: EwPduFL7NUSX-XO2IjLdbg.9RUaEtbA1QgGAMjm9zw7500O3uU.jWAAIWUqBbvBpUMw2fdlLwawmYZN62ief7cinujmQA29KE-ePsTGX
> hYLfHHA_V7fTHf-heKKI1A80EI_okdRMhQwKVxAbFhiF0ix8Phbd-BtIEYILD50QBTz3229tU5j2W7mqjqQ5xz_qmzP7XRNT89DYX6tTYQeRY1
> D7amWe9WJJqeamZQ98bHtYfUJhRSa61R7NTIfacOsCYtA4fV5UyFzZo894HbkWQm2rN9dYTv2YINFPbhBYRANw8PrZIb2UWjbI5GOAkfRXND1j
> G5S7dlj0LfsqjFIMt6uXM-NNfeaG3IdKhQmgofQXcw3_HZa-xL4RBj60pFukX-ZgTS8Fg
> userNone
> [2018-05-23 12:53:20,205] log: WARNING - Unauthorized: /oauth2/login
> [23/May/2018 12:53:20] "GET /oauth2/login?code=EwPduFL7NUSX-XO2IjLdbg.9RUaEtbA1QgGAMjm9zw7500O3uU.jWAAIWUqBbvB
> pUMw2fdlLwawmYZN62ief7cinujmQA29KE-ePsTGXhYLfHHA_V7fTHf-heKKI1A80EI_okdRMhQwKVxAbFhiF0ix8Phbd-BtIEYILD50QBTz32
> 29tU5j2W7mqjqQ5xz_qmzP7XRNT89DYX6tTYQeRY1D7amWe9WJJqeamZQ98bHtYfUJhRSa61R7NTIfacOsCYtA4fV5UyFzZo894HbkWQm2rN9d
> YTv2YINFPbhBYRANw8PrZIb2UWjbI5GOAkfRXND1jG5S7dlj0LfsqjFIMt6uXM-NNfeaG3IdKhQmgofQXcw3_HZa-xL4RBj60pFukX-ZgTS8Fg
>  HTTP/1.1" 401 12
>

**Comment by jobec** [comment]
Is that verbatim output from a django `runserver` session? Because I'm missing parts of the output and there seem to be multiple log formats through one another.

Also, make sure you added `django_auth_adfs` to the Django logging setting. Because it looks like the debug logs are not in the output.

**Comment by alejandroleonbauzo** [comment]
This is a copy paste from the console with redacted identifiable portions.

**Comment by alejandroleonbauzo** [comment]
Could it be the version of Django 2.1.1a?  I will try to downgrade to version 2.0.5 and try again.

**Comment by jobec** [comment]
Where does this come from?
```
[2018-05-23 13:03:29,193] log: WARNING - Unauthorized: /oauth2/login
```

**Comment by alejandroleonbauzo** [comment]
Turns out, the problem was either the version 2.1.1a of Django or other package.  I ended up blowing the virtual environment away and recreating it.  Installing pip packages one by one as needed.  This was caused by using pip upgrade facility in PyCharm.  sorry for the troubles and as always.  Thanks for your help!

**Comment by jobec** [comment]
I'll start adding Django 2.1 to the unit tests.
