### ISSUE TITLE
Active Directory Functional Level

### ISSUE THREAD

**Issue by rbohannonosc** [jobec/django-auth-adfs#39]
I currently have django-auth-adfs working using Active Directory Functional Level Windows Server 2008R2. My organization is planning to upgrade to the Windows Server 2016 functional level.

Is django-auth-adfs certified to run on the 2012R2 Domain Functional Level? 
Are you aware of any known bugs or issues running with 2012R2 Domain Functional Level?

Is django-auth-adfs certified to run on 2016 Domain Functional Level?
Are you aware of any known bugs or issues running with 2016 Domain Functional Level?

Thanks for your help.

**Comment by jobec** [comment]
I've tested it on both 2012R2 and 2016.

**Comment by rbohannonosc** [comment]
Thank you.
