### ISSUE TITLE
How to specify SIGNING_CERT in 1.x

### ISSUE THREAD

**Issue by drewhemm** [jobec/django-auth-adfs#40]
https://github.com/jobec/django-auth-adfs/blob/3a101b3509b3648e072ca103c56b61a1ec1420a6/django_auth_adfs/config.py#L53

The SIGNING_CERT option appears to have been deprecated. How should we now specify the custom certificate in use?

**Comment by jobec** [comment]
There is no need anymore to specify it. It's automatically loaded from the ADFS server based on the meta data it provides. It also resolves automatic key rollovers on the ADFS side without any manual action. Or in other words: it just works.

I'm open for discussion if you need this for some use case.

**Comment by jobec** [comment]
btw, nice to see you test that upcoming release already :)
One downside to Github is the lack of contact with your users. I can't ask people to do a test, unless I start with mailing lists and such. But that's a lot of overhead.

**Comment by drewhemm** [comment]
Screenshot attached of the debug output when I test the auth:

![screenshot from 2018-06-12 15-06-12](https://user-images.githubusercontent.com/4614943/41295377-5f88e442-6e52-11e8-925e-907540066ab1.png)

I saw the reference to 1.x in another [issue](https://github.com/jobec/django-auth-adfs/issues/25), so I thought I'd give it a try. So far I haven't been successful in any combination of versions or configuration :cry:

**Comment by jobec** [comment]
This error indicates that the certificate of the HTTPS connection towards your ADFS server isn't trusted.

This has nothing to do with the `SIGNING_CERT` setting (that was for the certificate that signed to access token, which isn't the one for the HTTPS connection).

Have a look at the `CA_BUNDLE` setting. That one default to `True`, meaning it takes whatever certificate bundle the `requests` package uses. You most likely want to point that setting to a file containing the root CA that signed the HTTPS certificate of your ADFS server.

**Comment by jobec** [comment]
I'll close this issue.

If you still have issues, feel free to reopen.
