### ISSUE TITLE
ADFS with no SLO support crashes this module

### ISSUE THREAD

**Issue by edevil** [jobec/django-auth-adfs#43]
I'm interacting with an ADFS server that has not installed [KB4038801](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-logout-openid-connect) (at least not yet). This means that the configuration object returned has no "end_session_endpoint" attribute and this module crashes at https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/config.py#L179.

Is there any way to still use this IDP without the SLO functionality?

**Comment by jobec** [comment]
The best way will be to catch the exception in `load_config()` and switch to ADFS 3.0 mode. (And emit a nice warning about KB4038801 being missing).

I'll see to get this fixed soon.

**Comment by jobec** [comment]
Can you test with the latest version from the master branch? It should be fixed now.

**Comment by edevil** [comment]
@jobec It works! Thanks.
