### ISSUE TITLE
 'TENANT_ID' is not a valid configuration directive - Question

### ISSUE THREAD

**Issue by unl1k3ly** [jobec/django-auth-adfs#49]
Hi, 

First of all, thank you so much for this project.

I'm trying to implement the Azure Integration using this https://github.com/jobec/django-auth-adfs/blob/master/docs/azure_ad_config_guide.rst guide.

I have all required information as per example:
```
AUTH_ADFS = {
    "TENANT_ID": "12345678-90ab-cdef-1234-567890abcdef",
    "CLIENT_ID": "480499d2-1f78-4a58-b7bc-03ebf8780af3",
    "RELYING_PARTY_ID": "https://examplecom.onmicrosoft.com/338d463b-b82f-490b-567890abcdef",
    "AUDIENCE": "https://examplecom.onmicrosoft.com/338d463b-b82f-490b-567890abcdef",
}
```

When I fire up Django, It gives me a TENANT_ID error...
```
django.core.exceptions.ImproperlyConfigured: 'TENANT_ID' is not a valid configuration directive
```
Have you experienced something like that ?

I would appreciate if you could help or at least point me to the right direction.

Thank you.

**Comment by jobec** [comment]
Which version did you install?

Azure support is experimental for the moment and needs 1.0.0rc2. By default pip doesn’t install that version unless you specify the version exactly.

pip install django-auth-adfs==1.0.0rc2

I’ll see on releasing a ‘normal’ version soon.

**Comment by unl1k3ly** [comment]
Thanks for clarifying. 

I've installed the rc2 version and it tenant_id error no longer bothers me. Although, I'm getting these now:
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: /tenant_id_redacted/.well-known/openid-configurati│  666 messagebu  20   0 50056  2680  2356 S  0.0  0.5
on (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe188ffc2b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name │20938 root       20   0  472M 16172  6820 S  0.0  2.7
resolution',))```
 
It seems it can't get the tenant url... Is there anything i could be doing ?

Thanks for all assistance mate.

Cheers

**Comment by jobec** [comment]
What does your config look like?

**Comment by unl1k3ly** [comment]
Similar to this one as per your example:

```
AUTH_ADFS = {
    "TENANT_ID": "12345678-90ab-cdef-1234-567890abcdef",
    "CLIENT_ID": "480499d2-1f78-4a58-b7bc-03ebf8780af3",
    "RELYING_PARTY_ID": "https://examplecom.onmicrosoft.com/338d463b-b82f-490b-567890abcdef",
    "AUDIENCE": "https://examplecom.onmicrosoft.com/338d463b-b82f-490b-567890abcdef",
}
```
When I request `https://login.microsoftonline.com/[ID]/.well-known/openid-configuration` manually, works.

Thanks

**Comment by unl1k3ly** [comment]
I think the bug is because you are using `settings.SERVER` rather than AZURE_AD_SERVER.

By setting `settings.SERVER = AZURE_AD_SERVER`, works,

**Comment by jobec** [comment]
It should be set here
https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/config.py#L95

**Comment by unl1k3ly** [comment]
I did set it at https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/config.py#L168 and works.. that's odd! I'll debug this one later.

**Comment by unl1k3ly** [comment]
I've hard coded in my environment by editing the package file config.py with the following function.

```
    def _load_openid_config(self):
        settings.SERVER = "login.microsoftonline.com"
        config_url = "https://{}/{}/.well-known/openid-configuration".format(
            settings.SERVER, settings.TENANT_ID
        )
``` 

Note that I've only added `settings.SERVER = "login.microsoftonline.com"`.

Cheers

**Comment by jobec** [comment]
https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/config.py#L93

There's a type in the word TENANT... try changing it to TENANT instead of TENNANT... :facepalm:

**Comment by unl1k3ly** [comment]
oh no! problem solved ! :P I will pull when you commit changes to a new version.

Now, the authentication works, but even returns it redirects me to a "login_wrong" template :/ as if authentication is not right... 

Anyways, I'll debug this further.

Thanks mate

**Comment by jobec** [comment]
The last version from the master branch should fix the issue. I'll see to release a new version soon also.

**Comment by jobec** [comment]
Checkout version `1.0.0rc3`

Feel free to open a new issue if you still have other issues
