### ISSUE TITLE
Does this package work with Django Rest Framework / Angular

### ISSUE THREAD

**Issue by blapsley** [jobec/django-auth-adfs#50]
I noticed that you mentioned it was on your plan to make this work with DRF. I didn't realize that was the case and tried to get it working but have only gotten to a "DEBUG:django_auth_adfs.backend:django_auth_adfs was called but no authorization code was received
"GET /oauth2/login HTTP/1.1" 401 12
WARNING:django.server:"GET /oauth2/login HTTP/1.1" 401 12"

Just wondering if this should work for DRF or if not do you know of any other options for DRF and ADFS integration

**Comment by jobec** [comment]
DRF support is not there yet. But it's still on my todo list.

It's not that difficult to implement, but I would like to have the Azure support sort of stable before adding DRF support.

**Comment by blapsley** [comment]
I am attempting to get this to work with DRF. I noticed your AUTH_ADFS settings are different than the documentation on github. Does REDIR_URI not useful anymore? In our attempt to specify one differently, we continue to get the same redirect uri due to the redirect_uri function in config.py

def redirect_uri(self, request):
        self.load_config()
        return request.build_absolute_uri(reverse("django_auth_adfs:callback"))

**Comment by jobec** [comment]
What do you mean with _your AUTH_ADFS settings_ ?

**Comment by blapsley** [comment]
no more REDIR_URI according to your readme, also Resource is renamed  RELYING_PARTY_ID?

**Comment by blapsley** [comment]
It looks like the redirect_uri is now being pulled via the url's file reverse uri from callback. if that is intended without specifying one now, i just wanted to know.

**Comment by blapsley** [comment]
Ah I just saw it was an alias.

**Comment by JonasKs** [comment]
Did you get this working with DRF @blapsley ? Would you like to share your solution?

**Comment by blapsley** [comment]
I ended up getting it to do what we needed it to do with our existing JWT framework. I more or less created our own django views and copied over code from. We were implementing ADFS into a self housed authentication website so my problem was a bit different.

**Comment by jobec** [comment]
Closing in favor of #54
