### ISSUE TITLE
client_secret support

### ISSUE THREAD

**Issue by quozd** [jobec/django-auth-adfs#52]
Hello, would you consider adding client_secret parameter support? It's required by ADFS for `Server application` application group when exchanging code for jwt token. (see https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers#web-browser-to-web-app).

I'll be happy to provide a PR with the fix if you are ok with it.

**Comment by jobec** [comment]
PRs are always welcome.

I'm just wondering though, what's your reason for using client secrets?
I'm also not sure whether client secrets are supported on windows 2012...

**Comment by quozd** [comment]
@jobec the reason is pretty simple: security requirements. Also it's recommended way for apps which consume other ADFS-protected services (service-to-service)

Client secret is optional. Unsupported servers will be consumed the same way as before.
