### ISSUE TITLE
Django Rest Framework integration

### ISSUE THREAD

**Issue by JonasKs** [jobec/django-auth-adfs#54]
Hello,
In the closed issue #21 you mention that integration with DRF is on your to-do list. Any progress on this the last year?
Everything works perfect on the Django part, but we would like to protect our API with the same logic as we use for front-end. 

If you have no intention to implement it in this package, but know how to make it possible, would providing some gists with example setup be possible?

**Comment by jobec** [comment]
I do intent to implement it. I just didn't find enough time yet to fully implement it 😞

**Comment by thenewguy** [comment]
Are you looking for API specific integration?

If you're using the api for a browser app you can use session based auth and any django authentication you like.

**Comment by thenewguy** [comment]
https://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication

**Comment by JonasKs** [comment]
Thanks for the reply, I hope you're able to find time to do so @jobec. 👍 

@thenewguy , we need applications and scripts to be able to use the APIs too. Currently looking into implementing the [oauth-toolkit](https://django-oauth-toolkit.readthedocs.io/en/latest/) in order to allow users register apps. This + sessions might be a solution, but I'm not 100% sure yet.

**Comment by jobec** [comment]
While sessions work, a typically REST call should be stateless. Using sessions violates this principle.

The way I intent it to work is by looking for a JWT bearer token in every request and use it to authenticate the client. This also allows you to scale across multiple servers without a need for a common session store (e.g. a database or shared file system)

**Comment by jobec** [comment]
I found time to implement a first version of rest framework support.

Please test it if you can. All feedback is welcome.

Docs: 
https://github.com/jobec/django-auth-adfs/blob/DRF_support/docs/rest_framework.rst

Notice: the example script at the end of the above page works only for Windows server 2016 as it's the first version to implement the `Resource Owner Password Credentials Grant`.

**Comment by JonasKs** [comment]
Hey, thanks for the quick response and prototype. I'm out of town for a week, but will come back to you next monday.
Have a good weekend!

**Comment by jobec** [comment]
I forgot to mention: the code is in the **DRF_support** branch

**Comment by maerteijn** [comment]
I looked and tested the `DRF_support` branch and I think it's nicely done. The `AdfsAccessTokenAuthentication` implementation is clean and simple and straight forward. Personally I would split the `AdfsBackend` backend into two backends instead of having two types of authentication types in one method. This way you can choose which backend(s) you want to have enabled.

So:
```python
class AdfsBackend(ModelBackend):

    def authenticate(self, request, authorization_code=None, access_token=None, **kwargs):
        ....
```
could be something like:
```python
class AdfsAuthCodeBackend(AdfsBackend):

    def authenticate(self, request, authorization_code=None, **kwargs):
        ....

class AdfsAccessCodeBackend(AdfsBackend):

    def authenticate(self, request, access_token=None, **kwargs):
        ....
```

(or with different names when you want to stay backwards compatible of course)

**Comment by jobec** [comment]
That's actually a good idea. You now indeed have to choose between A or A+B, you can't choose B.

And it can still be DRY by having `AdfsAuthCodeBackend` inherit from `AdfsAccesTokenBackend` and only put the exhange-auth-code-for-token code in there.

Let's see what I can do...

**Comment by JonasKs** [comment]
Is (file: `backend.py`) 
```py
        signals.post_authenticate.send(
            sender=self,
            user=user,
            claims=claims,
            adfs_response=adfs_response
        )
```
supposed to be 
```py
        signals.post_authenticate.send(
            sender=self,
            user=user,
            claims=claims,
            adfs_response=access_token
        )
```
? 
If not, I get `UnboundLocalError: local variable 'adfs_response' referenced before assignment`
Full trace:
```py
DEBUG 2018-11-26 12:05:07,165 django_auth_adfs Attribute 'testuser' for user 'first_name' was set to 'Test'.
DEBUG 2018-11-26 12:05:07,165 django_auth_adfs Attribute 'testuser' for user 'last_name' was set to 'Some Lastname'.
DEBUG 2018-11-26 12:05:07,166 django_auth_adfs Attribute 'testuser' for user 'email' was set to 'test@testuser.com'.
Internal Server Error: /api/api/test/
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\rest_framework\views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\rest_framework\views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\rest_framework\views.py", line 400, in initial
    self.perform_authentication(request)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\rest_framework\views.py", line 326, in perform_authentication
    request.user
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\rest_framework\request.py", line 223, in user
    self._authenticate()
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\rest_framework\request.py", line 376, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django_auth_adfs\rest_framework.py", line 38, in authenticate
    user = authenticate(access_token=auth[1])
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\contrib\auth\__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django_auth_adfs\backend.py", line 77, in authenticate
    adfs_response=adfs_response
UnboundLocalError: local variable 'adfs_response' referenced before assignment
[26/Nov/2018 12:05:07] "GET /api/api/test/ HTTP/1.1" 500 25313
```

It also does not set frist_name or email in the database?
![image](https://user-images.githubusercontent.com/5310116/49010548-e62c5c00-f173-11e8-8a4e-ca6771b6b899.png)

If I change it, I how ever get this error:
```py
ValidationError at /oauth2/callback

{'password': ['This field cannot be blank.']}
```

Full trace:
```py
DEBUG 2018-11-26 12:11:41,777 django_auth_adfs Attribute 'testuserb' for user 'first_name' was set to 'testuserb'.
DEBUG 2018-11-26 12:11:41,777 django_auth_adfs Attribute 'testuserb' for user 'last_name' was set to 'Some Name B'.
WARNING 2018-11-26 12:11:41,777 django_auth_adfs Claim 'email' for user field 'email' was not found in the access token for user 'testuserb'. Field is not required and will be left empty
Internal Server Error: /oauth2/callback
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django_auth_adfs\views.py", line 34, in get
    user = authenticate(request, authorization_code=code)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\contrib\auth\__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django_auth_adfs\backend.py", line 80, in authenticate
    user.full_clean()
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\oauthminimal\lib\site-packages\django\db\models\base.py", line 1151, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'password': ['This field cannot be blank.']}
[26/Nov/2018 12:11:41] "GET /oauth2/callback?code=somelongcode HTTP/1.1" 500 105833

```

Again, the first and last name is not in the database. 

I'll try to create a completely new project as this was just tried to be implemented in my previous test project.

**Comment by JonasKs** [comment]
Seems like #57 fixes `django.core.exceptions.ValidationError: {'password': ['This field cannot be blank.']}`.

This also fixes database errors where first_name and email was not inputed correctly.

Still unsure if `adfs_response` should be `adfs_response=access_token` or not.

**Comment by maerteijn** [comment]
@JonasKs adfs_response should not be access_token as it's the response from the ADFS server which INCLUDES the access token

**Comment by JonasKs** [comment]
```py
    adfs_response = response.json()
    access_token = adfs_response["access_token"]
else:
    access_token = access_token.decode()
logger.debug("Received access token: " + access_token)
```
Seems like it is intended to be `access_token`, to me? `adfs_response` is not used for anything but creating the `access_token` variable. 

I'm using the [DRF branch.](https://github.com/jobec/django-auth-adfs/blob/DRF_support/django_auth_adfs/backend.py#L57)

**Comment by jobec** [comment]
There seems to be some code messed up in the DRF branch because of some merge conflicts while merging. I'll see to fix this in the coming days.

Bus as @maerteijn mentions, it should indeed be the entire adfs response that's passed to the signal. Not just the token.

**Comment by JonasKs** [comment]
I see. I'll await your merges into master then, since everything else works fine. I guess we also can push 1.x to pypi when that is done too?

**Comment by maerteijn** [comment]
This will fix the `DRF_support` branch: https://github.com/jobec/django-auth-adfs/pull/59

**Comment by JonasKs** [comment]
Thanks mate. Confirmed that #59 fixes the issue.

**Comment by maerteijn** [comment]
@jobec If you need any help in fixing the `DRF_support` branch with the merge conflicts and the splitted backends I'm happy to do so and create a pull request for it.

If so, maybe you could indicate which names you prefer for the backends (and baseclass if needed) and if you would like to stay backwards compatible (keep the name `AdfsBackend` intact).

**Comment by jobec** [comment]
I've already got some code prepared. But needs some fine-tuning and documentation still. Stay tuned, I'm almost ready.

**Comment by JonasKs** [comment]
Awesome! I'll test all of this tomorrow morning 😄

**Comment by jobec** [comment]
Did you add the authentication class to the DRF settings?
https://github.com/jobec/django-auth-adfs/blob/DRF_support/docs/rest_framework.rst

Also, you'll need to change your Django settings to this:

```python
AUTHENTICATION_BACKENDS = (
    ...
    'django_auth_adfs.backend.AdfsAccessTokenBackend',
    ...
)
```

**Comment by JonasKs** [comment]
Can confirm that it now works as expected. My bad. 

No further issues so far, going to implement it to main project. Thank you!

**Comment by jobec** [comment]
Then I'll work on the docs and hopefully release v1 this week.

**Comment by JonasKs** [comment]
Any thoughts on adding an API and the paths for getting a token and refreshing it too?

e.g.


`views.py`
```py
from rest_framework.request import Request
from rest_framework.views import APIView
from rest_framework.response import Response
from shared.helpers.views import generate_error_response
import logging
from rest_framework.permissions import AllowAny
from api_auth.services.get_token import get_jwt_token
from api_auth.utils import is_valid_username
from api_auth.exceptions import InvalidUsernameOrPassword


class AuthenticateAPI(APIView):
    """
    Authenticates a user towards ADFS
    """
    # Allowing anyone to use this function.
    permission_classes = [AllowAny]

    def post(self, request: Request):
        """
        Takes a POST request with a json body, formed like this:
        "username": `username`
        "password": `password`
        :param request: The request
        :return: A JWT token generated by ADFS
        """

        # Verify that the request contains parameter `username`.
        param_username = request.data.get('username', None)
        if param_username is None:
            return generate_error_response('Attribute `username` is required', 400)
        if not is_valid_username(param_username):
            return generate_error_response(
                'Attribute `username` contains an invalid username.', 400)

        # Verify that the request contains parameter `password`.
        param_password = request.data.get('password', None)
        if param_password is None:
            return generate_error_response('Attribute `password` is required', 400)

        token = None
        try:
            token = get_jwt_token(param_username, param_password)
        except InvalidUsernameOrPassword:
            return generate_error_response("Username or password was invalid.", 400)

        except Exception:
            generate_error_response("Uncaught error occurred", 500)

        return Response(token, 200)
```


`api_auth/services/get_token.py`
```py
import requests
from decouple import config
from api_auth.exceptions import InvalidUsernameOrPassword


def get_jwt_token(username, password):
    """
    Authenticates a user towards ADFS and returns a json body with token information.
    :param username: users username, such as `testuser`
    :param password: users password, such as `verystrongpassword123`
    :return:
    """

    # Get an access token
    payload = {
        "grant_type": "password",
        "resource": config('ADFSResource'),
        "client_id": config('ADFSClient'),
        "username": username + "@domain.com",
        "password": password,
    }

    get_response = requests.post(
        "https://adfs.example.com/adfs/oauth2/token",
        data=payload,
    )

    # OK
    if get_response.status_code == 200:
        response_data = get_response.json()
        json_body = {
            'access_token': response_data['access_token'],
            'expires_in': response_data['expires_in'],
            'refresh_token': response_data['refresh_token'],
            'refresh_token_expires_in': response_data['refresh_token_expires_in'],
            'token_type': response_data['token_type']
        }
        return json_body

    # 400, aka invalid username or pw
    elif get_response.status_code == 400:
        raise InvalidUsernameOrPassword()

    else:
        # TODO: Log exception!!
        raise Exception
```

**Comment by JonasKs** [comment]
It seems to me that its the easiest way to allow other users within the company to use the API without needing these variables?
```py
"resource": "your-relying-party-id",
"client_id": "your-configured-client-id",
```

The idea was initially gained from reading the refresh-token code [here](https://github.com/jobec/django-auth-adfs/pull/55#issuecomment-440442314). 

All we need is a way to authenticate users before allowing them to use the API. In each API file I can specify AD groups like this:
```py
class TestOwnership(BasePermission):
    """
    Object-level permission to only allow users that are in the `I2.App.NSPortal.ReadWrite` group.
    """

    def has_permission(self, request, view):
        return request.user.groups.filter(name='ReadWriteAccess')
```

If not, why is this not a good idea, compared to e.g. implementing Oauth2 (as I had before).

**Comment by jobec** [comment]
If you want AD integration, then you can use django-auth-adfs. But...

Take a look at the RFC first: https://tools.ietf.org/html/rfc6749#section-1.2

### Regular Django
In the regular case, without DRF support and an API, Django serves as both `Client` and `Resource Server`. Your user is the `Resource Owner` and ADFS is the `Authorization server`.

* A client needs a `client_id` to identify itself at the `Authorization server`
* ADFS needs a `resource` id to identify what `resource server` the client wants access to. (*This is an extra parameter specific to ADFS!!*)  This value ends up as the `audience` claim in the access token which is validated but the resource server to prevent using an access token meant for another resource server.

### Django Rest Framework
In the case with DRF and an API, the roles shift.
Django DRF is not the `client` anymore but only the `Resource Server`.
The client role shifts to whatever consumes your API (e.g. a script, other server, other application, ...)

But things remain the same, the client still needs an `client_id` and needs to tell ADFS for which resource server it wants an access token.

So, in this case, you need to register your client (e.g. a script, other server, other application, ...) in ADFS, give it a unique client ID and give it access to the `resource server`.

See this screenshot: https://github.com/jobec/django-auth-adfs/blob/DRF_support/docs/_static/2016/05_review_settings.png

I hope this makes things a bit more clear?

**Comment by JonasKs** [comment]
Got it! 
Registered third party clients as unique IDs and gave it access. I no longer have to be a middleman and handling user/pw, which is nice. Thanks a lot :)

**Comment by jobec** [comment]
I should add that to the documentation also... I think a lot of people don't completely know how that OAuth2 stuff works in combination with ADFS.

**Comment by JonasKs** [comment]
^ Agreed. Appreciate your explanation and help this week! ⭐️

**Comment by jobec** [comment]
Almost there!

I added some more indepth details about OAuth2, Django and ADFS.
https://github.com/jobec/django-auth-adfs/blob/DRF_support/docs/oauth2_explained.rst

I still need to expand the DRF part a bit, but all feedback is welcome already.

**Comment by maerteijn** [comment]
I have to say it’s really, really well written (in clean and understandable English). Especially the parts where you map the vague OAuth2 terms to what they mean in real scenarios with Django: The graphs you added there are helping a lot.

It took me a long time in the past to understand the complete flow(s) including all the roles. Especially with the different grant types and when to use them.

I wished this documentation you wrote already existed back then, it would have speeded up the process of understanding A LOT 🙂

So 👍!

**Comment by JonasKs** [comment]
Looks great! Very clear and well written. 

One last question from my side: How would you test API if forced authentication on it?
At the moment, all my tests break with `'Authentication credentials were not provided.`, obviously.

**Comment by jobec** [comment]
You need to retrieve an access token from ADFS and send it as a Bearer Token in the Authorization Header in the request. [See the RFC here](https://tools.ietf.org/html/rfc6749#section-7.1)

Have a look at this script for how to do it: https://github.com/jobec/django-auth-adfs/blob/DRF_support/docs/rest_framework.rst#requesting-an-access-token

**Comment by maerteijn** [comment]
With DRF tests you can send the header with the APIClient like this:
```python
    client = APIClient()
    client.credentials(HTTP_AUTHORIZATION="Bearer {}".format(access_token)
```

**Comment by JonasKs** [comment]
Awesome, thanks guys!

**Comment by jobec** [comment]
Version 1.0.0 is released.
closing this issue.

**Comment by JonasKs** [comment]
@jobec , I see you have made a `@mock_adfs` wrapper. I have tried to implement it, hoping I could avoid actually having dependencies in my tests. It keeps using my real ADFS, how ever. I looked at your [code](https://github.com/jobec/django-auth-adfs/blob/master/tests/test_drf_integration.py#L37), but no success. Also no success when I tried to run your code directly. 

Can you spot what I'm missing?
```
python manage.py test shared.tests.tests.test_drf_integration  
Creating test database for alias 'default'... 
System check identified no issues (0 silenced). 
EEEE 
======================================================================
ERROR: test_access_token_2012 (tests.test_drf_integration.RestFrameworkIntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last): 
  File "tests/utils.py", line 215, in wrapper
    test_func(*original_args, **original_kwargs)
  File "tests/test_drf_integration.py", line 32, in test_access_token_2012
    user, token = self.drf_auth_class.authenticate(request)
  File "lib/python3.7/site-packages/django_auth_adfs/rest_framework.py", line 40, in authenticate
    user = authenticate(access_token=auth[1])
  File "lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate 
    user = backend.authenticate(request, **credentials)
  File "lib/python3.7/site-packages/django_auth_adfs/backend.py", line 278, in authenticate
    provider_config.load_config()
  File "lib/python3.7/site-packages/django_auth_adfs/config.py", line 158, in load_config
    loaded = self._load_openid_config()
  File "lib/python3.7/site-packages/django_auth_adfs/config.py", line 190, in _load_openid_config
    response = self.session.get(config_url, timeout=settings.TIMEOUT) 
  File "lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "lib/python3.7/site-packages/elasticapm/instrumentation/packages/base.py", line 136, in call_if_sampling
    return wrapped(*args, **kwargs)
  File "lib/python3.7/site-packages/requests/sessions.py", line 646, in send 
    r = adapter.send(request, **kwargs)
  File "lib/python3.7/site-packages/responses.py", line 626, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "lib/python3.7/site-packages/responses.py", line 601, in _on_request
    raise response 
requests.exceptions.ConnectionError: Connection refused by Responses: GET https://adfs.MY_ACTUAL_ADFS.com/adfs/.well-known/openid-configuration doesn't match Responses Mock"""
```

Currently (working) setup with real ADFS requests to authenticate, and what I'd like to have mocked:
```python
access_token = get_adfs_access_token()
class TestBase(APITestCase):
    def call_endpoint(self, data=None):
        path = '/api/'
        self.client = APIClient()
        self.client.credentials(HTTP_AUTHORIZATION="Bearer {}".format(access_token))
        return self.client.post(path, data, content_type='application/json')

class SuccessTests(TestBase):
    def test_something(self):
        expected_body = {'some': 'json'}
        body = json.dumps({'input':'json'})
        response = self.call_endpoint(data=body)
        self.assertEqual(response.data, expected_body)
```

**Comment by jobec** [comment]
Make sure your request matches a registered regex in Responses.
I would also use a fake (example.com style) address for your ADFS url. That way it breaks more predictable.

**Comment by jobec** [comment]
Also, instead of mocking ADFS, it might be easier to just build an JWT access token yourself (it’s also in the test code you link to). Your test just needs a valid token, not an entire ADFS server.

**Comment by jobec** [comment]
I overlooked one thing, django_auth_adfs automatically loads settings from the ADFS server. Hence, it won’t trust any JWT token you create.

 This is indeed a show stopper if you want to test an API with this module integrated...

**Comment by JonasKs** [comment]
Yeah, exactly what I experienced, hehe.     
I might just have work around it and have something like `if 'test' in sys.arv: <disable ADFS>` . My build environment will probably not have access to ADFS soon, so I don't have much of a choice but either disable it or mock it.

**Comment by jobec** [comment]
Mind opening a separate issue for it? I’ll see what I can do.
I was busy refactoring the test suite, so maybe I can make it reusable somehow.

You might also be able to mock some functions in the django_auth_adfs classes so it doesn’t load anything from the adfs server and instead load the setting by monkey patching or so.

**Comment by JonasKs** [comment]
For sure! I’ll create it tomorrow morning and look into some more mocking as well. Thanks :)
