### ISSUE TITLE
Unable to sign in with Azure AD

### ISSUE THREAD

**Issue by wfoord** [jobec/django-auth-adfs#62]
I get the following error once I click on login:

Sorry, but we’re having trouble with signing you in.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx'. <--- 

> the application ID is the native app on Azure

My settings are
```

LOGIN_URL = 'django_auth_adfs:login'
LOGIN_REDIRECT_URL = '/'


MIDDLEWARE = [
    '...
'django_auth_adfs.middleware.LoginRequiredMiddleware',
]


AUTH_ADFS = {
    "LOGIN_EXEMPT_URLS":["^system/admin/",
                         "^account/login/"
                         "^oauth2/login/",
#                         "^oauth2/callback/",
                         ],
    "TENANT_ID": "xxxxx",
    "CLIENT_ID": "xx",
    "RELYING_PARTY_ID": "https://xxxx.onmicrosoft.com/xxxx-xxxx-xxx",
    "AUDIENCE": "https://xxxx.onmicrosoft.com/xxxx-xxxx-xxxx-xxxx",
    "CLAIM_MAPPING": {"first_name": "given_name",
                     "last_name": "family_name",
                     "email": "email"},
    "REDIR_URI": "https://our-website.com/oauth2/callback",
}

```
The query string parameters in the URL has redirect_uri as: **http://our-website.com/oauth2/callback**

In Azure the reply url is set to **https://our-website.com/oauth2/callback**

Is there anything that I'm missing? Should I specify this reply url somewhere in my settings? 
Django 1.11 and django-auth-adfs 1.0.0

Please let me know if you need any more info from my side

**Comment by jobec** [comment]
I guess you figured it out already?

Feel free to share what the issue was. Might be interesting to document in the FAQ...

**Comment by wfoord** [comment]
We managed to integrate django_auth_adfs in our system. And partly it's also working with Azure AD.
but sometimes we got the following error:
ADFS server returned an error: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '*******-*****-****-****-0c4812*****'.

Azure AD is configured with conditional access rules. When you are in a trusted location you don't have to enter 2FA, but if you are not on a trusted location you have to enter 2FA.
When you are on a NOT trusted location, you can login fine.
When you are on a trusted location we got the error above.
```ADFS server returned an error: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '*******-*****-****-****-0c4812*****'.```
Things we tried:
- disable trusted location. (Then you can login)
- exclude the user from conditional access rule. (then you can login)
- disable 2 factor authentication for the user. (then you can login)

We found an article from Microsoft that explains exactly what happens:

https://docs.microsoft.com/en-us/azure/active-directory/develop/conditional-access-dev-guide#scenario-app-performing-the-on-behalf-of-flow
