### ISSUE TITLE
Duplicate Key Integrity Error - Second login and beyond

### ISSUE THREAD

**Issue by Mabritoj** [jobec/django-auth-adfs#63]
Working on a Django project (specifically with the Saleor framework) and looking to authenticate against our ADFS 2016 servers.  I can get the authentication to work, but only when the user logs in for the first time. After they log in for the first time, proceeds to log out, and tries to log in again...a "duplicate key value violates unique constraint "userprofile_user_email_key" IntegrityError is thrown. The details says the email address already exists. 

```
Request Method: | GET
-- | --
http://localhost:8000/en/oauth2/callback?code=yRuy1iPDyUu3PlGaHqcHpw.l0dBl0hc1ghgAPxu-bZKE6AXCIY.gf96MEQm8zNy8IJQGotqh1JiBshH5n7WOC8ivsqPiPafJvakuapOmRtyj1_V92nUFjN6xgXgOkcI-TSwHQu6wfrIva5nMTf6dvMU9qFWji3Gy1jdn8zVhgh4x2kTyjialSKPsWEXhdrkESm9VaHPVl17j5Y89MlTqJpF2H6FJkKx0w1yACjsbf9Ua8vI3haVHd45UGqy8ElOSmPSYhXmPzLgyStBXQqKGXU_B7FJ8WLRSIqA2DDPi07BLPtACyeCPyXboaGl-ZoUcZtyv3T4af2fkwzzHy3OB387BbVIJFLahrFgDGAPdV5bdevfe_YMVXSzHpx34xEDaD4OH9UIBQ&state=Lw==&client-request-id=785f2896-595c-40f2-e731-0780010000fc
2.1.3
IntegrityError
duplicate key value violates unique constraint "userprofile_user_email_key" DETAIL:  Key (email)=(emailaddress@email.com) already exists.
/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
/usr/local/bin/python
3.6.7
['/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/app']
Fri, 7 Dec 2018 07:33:36 -0600
```

Its my understanding (please correct me if im wrong), when a user a logs in via ADFS, if the user doesn't exist...the user will be created in the Django Postgres database. If the user does exist, a "mapping" will happen and associate the ADFS user to the existing user in the Django Postgres database?

Our AUTH_ADFS config is as follows (had to scrub our information):
```python
AUTH_ADFS = {
    "SERVER": "scrubbed URL",
    "CLIENT_ID": "scrubbed client_ID",
    "RELYING_PARTY_ID": "scrubbed relying party ID",
    "AUDIENCE": "microsoft:identityserver:scrubbed",
    "CA_BUNDLE": "/app/ca-bundle.pem",
    "CLAIM_MAPPING": {"email":"email"},
    "GROUP_TO_FLAG_MAPPING": {"is_superuser": "Admins"},
    "CONFIG_RELOAD_INTERVAL": 0.1
}
```
Any ideas?

**Comment by jobec** [comment]
Which version of django-auth-adfs are you using?

**Comment by Mabritoj** [comment]
We are using 1.0.0 that was just released on Dec 5

**Comment by jobec** [comment]
Do you have a proper full traceback from CLI?
Your example above is a copy paste from the debug internal server error page I guess?

**Comment by Mabritoj** [comment]
Correct...that is from the debug internal server page. Probably should of uploaded me.

I copied out the CLI output and also saved the debug HTML page and put it [here](https://drive.google.com/drive/folders/1E1MedukH6YQckF5JuGeberuIBCfjVgDC?usp=sharing) for download.

**Comment by jobec** [comment]
Do you perhaps use a custom Django user model?

https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/backend.py#L121-L126

The code assumes that the `USERNAME_FIELD` is the primary key for the user model.
cfr: https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD

**Comment by Mabritoj** [comment]
Looking at Saleor framework, yep the user model looks custom and the framework set the email field to be unique and the primary key:

class User(PermissionsMixin, AbstractBaseUser):
    **email = models.EmailField(unique=True)**
    addresses = models.ManyToManyField(
        Address, blank=True, related_name='user_addresses')
    is_staff = models.BooleanField(default=False)
    token = models.UUIDField(default=get_token, editable=False, unique=True)
    is_active = models.BooleanField(default=True)
    note = models.TextField(null=True, blank=True)
    date_joined = models.DateTimeField(default=timezone.now, editable=False)
    default_shipping_address = models.ForeignKey(
        Address, related_name='+', null=True, blank=True,
        on_delete=models.SET_NULL)
    default_billing_address = models.ForeignKey(
        Address, related_name='+', null=True, blank=True,
        on_delete=models.SET_NULL)

    USERNAME_FIELD = 'email'

So the USERNAME_FIELD is there, just not primary key.

Looking at the Settings Reference, there is no way to set a custom primary key I assume (the code also looks static)? If I made the change for "usermodel.USERNAME_FIELD: claims[username_claim]" to be "usermodel.email: claims[username_claim]" do you see any issues stemming from it?

**Comment by Mabritoj** [comment]
I uploaded ([URL](https://drive.google.com/drive/folders/1E1MedukH6YQckF5JuGeberuIBCfjVgDC?usp=sharing)) the cli with db logging enabled. Looking thru it myself...I do not see it trying to double insert...but erroring out on an update statement?

**Comment by jobec** [comment]
I've added some verification code and tests to catch your issue.
If you use the latest version from the master branch, you'll see it raises an `ImproperlyConfigured` exception because you try to set the username field of the user model via a claim mapping.
