### ISSUE TITLE
Azure AD wants a new refresh token (AADSTS54005)

### ISSUE THREAD

**Issue by r-peschke** [jobec/django-auth-adfs#68]
Authenticating against an Azure AD-Directory I'm getting this response: 
**django_auth_adfs ERROR ADFS server returned an error: AADSTS54005: OAuth2 Authorization code was already redeemed, please retry witha new valid code or use an existing refresh token.**
I found [this](https://social.msdn.microsoft.com/Forums/azure/en-US/4192e141-309a-4dd6-a5c9-f1a8ce32f4ca/aadsts54005-oauth2-authorization-code-was-already-redeemed?forum=WindowsAzureAD) on Microsoft Forum. 
Is this a known problem and is there a solution?

**Comment by jobec** [comment]
Are you perhaps browsing to a url in your browser's history that has an old authorization code in it?

**Comment by jobec** [comment]
As expected, the only way I can trigger this error is when I go to a previous callback URL in my browser history containing an already exchanged authorization code.

So, make sure you trigger a fresh login from your application instead of using a URL in your browser history.

**Comment by r-peschke** [comment]
Thank you very much!
My problem is that the problem only happened  with the testers, it found it in the log files. But I also saw that they, 3 persons) never have been signed on in the application (Even missing a created user account in Django). And all my tests succeeded without any problems.
I will try to test it this way and again,
thank you very much for your good work
Ralf

**Comment by mkane848** [comment]
I'm currently running into this issue - it started at the same time I ran a management command that checks some user data against AD and suddenly everyone is getting the AADSTS54005 error.

Tried opening a different browser, clearing my cache/browsing data, etc. and it's still not letting anyone log in. I've occasionally seen the error pop up for a user, but seems like it was never a persistent problem.

Please let me know if more information would help clear some things up, I openly admit I've found myself in a "I literally didn't change anything and I'm not sure where to even start looking" situation, so any assistance is much appreciated. Will update ASAP if I find a resolution.

**Comment by jobec** [comment]
If you run into this again, try going through the troubleshooting guide: https://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html

Debug logs should give a hint where the issue is situated.
