### ISSUE TITLE
Not able to return https for redirect_uri

### ISSUE THREAD

**Issue by hitenjadeja** [jobec/django-auth-adfs#69]
Not able to return https for redirect_uri:
`def redirect_uri(self, request):
    self.load_config()
    return request.build_absolute_uri(reverse("django_auth_adfs:callback"))
`
https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/config.py#L259

Currently manually replacing http to https
`def redirect_uri(self, request):
    self.load_config()
    return request.build_absolute_uri(reverse("django_auth_adfs:callback")).replace("http://", "https://")
`

Im assuming ive missing a setting in either django or django-auth-adfs... scratching my head.

If there isn't an option could a fix be to add a setting?

**Comment by jobec** [comment]
How are you running Django? Gunicorn? uWSGI?

Have a look at this setting: https://docs.djangoproject.com/en/2.1/ref/settings/#secure-proxy-ssl-header

**Comment by hitenjadeja** [comment]
using Gunicorn, will test that setting and get back to you

**Comment by hitenjadeja** [comment]
So I have Nginx - Gunicorn - Django

Didn't work in changing it to https

**Comment by jobec** [comment]
You should configure nginx to set the x-forwarded-proto header, that should do the trick, along with that setting I mentioned before.

**Comment by hitenjadeja** [comment]
You sir... are AWESOME!

Thank you, so much!
