### ISSUE TITLE
only wheel package available on pypi for 0.1.0

### ISSUE THREAD

**Issue by mislavcimpersak** [jobec/django-auth-adfs#7]
Could you please add `.tar.gz` package on pypi since latest version (0.1.0) is not available when doing `pip install django-auth-adfs`? It installs 0.0.5 version.

[Here](https://pypi.python.org/simple/django-auth-adfs/) can be seen that only `.whl` package was created in latest build.

**Comment by jobec** [comment]
Fixed.



Very weird, because I've build both the weel and the source package and made twine upload both of them... Must be some error I've missed somehow.

Thanks for informing me!

**Comment by mislavcimpersak** [comment]
Thank for the quick response!
