### ISSUE TITLE
ConnectionError preventing login

### ISSUE THREAD

**Issue by mkane848** [jobec/django-auth-adfs#71]
Good morning,

Did what I could to verify that this wasn't something easily fixable, but one of my two sites using auth-adfs is having issues this morning:

`HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /<tenant-id>/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x042E97D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))`

I haven't changed anything, and the other site using an identical setup isn't currently facing any issues. Did I misconfigure something or am I missing something obvious?

Let me know if you'd like me to post any more of the traceback, I'll update this with anything else I find relevant.

Thank you!

**Comment by jobec** [comment]
It sounds like your server can't do a lookup of `login.microsoftonline.com` for some reason. (hence the `getaddrinfo failed` error).

Can you lookup `login.microsoftonline.com` from that system? A simple ping should tall you already if it's possible.

**Comment by mkane848** [comment]
....Strangely enough, after looking into it for an hour on my own, the second I submit the bug report the problem goes away -_- Still curious as to what happened, but with the imminent threat out of the way I

**Comment by mkane848** [comment]
Thanks for the quick reply, and apologies- looks like it was a DNS rule on the server was misconfigured and had nothing to do with me. I was able to ping but was initially told that nothing had changed overnight so I started to question reality lol
