### ISSUE TITLE
Templates not included

### ISSUE THREAD

**Issue by sergei-maertens** [jobec/django-auth-adfs#72]
Despite https://github.com/jobec/django-auth-adfs/commit/8baf088be751dce54f8e7a1d6c6d28af512ff953, it looks like the templates are still not included in the latest published PyPI package:

```bash
pip freeze | grep adfs
django-auth-adfs==1.1.2
```
```bash
ls $VIRTUAL_ENV/lib/python3.6/site-packages/django_auth_adfs/
backend.py  drf-urls.py  middleware.py  rest_framework.py  urls.py
config.py   __init__.py  __pycache__    signals.py         views.py
```
As you can see, the `templates` dir isn't present.

**Comment by jobec** [comment]
That actually is a bug I discovered in setuptools... https://github.com/pypa/setuptools/issues/436

I'm about to release a new package including the template.

**Comment by jobec** [comment]
Checkout v1.2.0
It contains the templates now.
