### ISSUE TITLE
Question: can I map a group that's comming from ADFS to an other group in Django

### ISSUE THREAD

**Issue by CorHortensius** [jobec/django-auth-adfs#75]
Hello
I got a question:
is it possible to map a group that is send with the GROUPS_CLAIM: group to another manual created group in Django.

**Example:**
adfs sends in the `groups_claim: "group"` a list of groups{ADgroup1, Adgroup2}
in Django I already manural created those groups: {Dgroup1, Dgroup2}
Now I want to map Dgroup1 to ADgroup2
So I was looking for something like this:
```
GROUP_TO_MAPPING{"Dgroup1": "ADgroup2",
                 "Dgroup2": "ADgroup1"}
```

Is this already in, of should it be created ?

it is simulair to the GROUP_TO_FLAG_MAPPING

I already played with the GROUP_TO_FLAG_MAPPING
`GROUP_TO_FLAG_MAPPING {"is_staff": "ADgroup2"}` And that is working as it should, but not with a manual created group.

**Comment by jobec** [comment]
It's not an existing feature.

In limited setups this kind of renaming might work, but I rather think it's easier to just create groups with the same name.

**Comment by CorHortensius** [comment]
oke, thanks for the reply.
We now created some internal code to match groups. When I have time, will try to add it to the package , so other's can also use it.
