### ISSUE TITLE
Can you add the note to  DRF integration page that integration is not available to ADFS 2012 R2  Server .

### ISSUE THREAD

**Issue by Sahilshetye** [jobec/django-auth-adfs#76]
Since the  ADFS 2012 R2  does not support Resource Owner Password Credentials Grant Type.
Can this  be added as a note to the documentation

**Comment by jobec** [comment]
Actually, it "does" work with ADFS 2012 R2.
It's just the code example that uses a flow not supported by ADFS 2012.
If you would modify it to use some other flow that is supported, you can just as well use 2012.

**Comment by Sahilshetye** [comment]
All the  documentation that I have read including yours only mentions that ADFS 2012 R2 only supports [authorization_code grant flow](https://django-auth-adfs.readthedocs.io/en/latest/oauth2_explained.html#oauth2-vs-openid-connect) which doesn't seem to be useful to me since I need to access the resource server programmatically.



  **I am a complete oAuth newbie and learning new stuff. Any advice on my understanding is appreciated.** 
For me, I just need the programmatic way of getting access token without having to open a browser to enter creds. Since the only  authorization_code is an accepted form of the grant type I always need to get authorization_code first to ask for access_token and then go ahead and ask for access_token and then use the token to query REST API. But getting  Authorization_code requires me to use a browser to log in every time for the access with a redirect_uri requirement. Is there no way of bypassing that?

**Comment by jobec** [comment]
I've got some legacy code to request a token using the Auth code grant. I'll see on adding it.

**Comment by Sahilshetye** [comment]
Sweet!! That will help a lot.

**Comment by jobec** [comment]
https://django-auth-adfs.readthedocs.io/en/latest/rest_framework.html
Bottom of the page
