### ISSUE TITLE
Mocking ADFS under testing

### ISSUE THREAD

**Issue by JonasKs** [jobec/django-auth-adfs#78]
At the moment my `setUp` includes fetching a valid `access_token` from ADFS, when I'd like to mock it. I've tried some monkey patching, but with no success so far. 

Any insight or thoughts on how to solve this would be appreciated, as sometime in the future my build and test servers will most likely not have access to ADFS. The workaround would be to disable auth during tests, which I'd rather not do.

**Comment by JonasKs** [comment]
To add to this issue, my dream scenario would be:  
1) Create a JWT that has group claim of ala `APIAdmin`
2) Write a POST test, it should work due to the group claim
3) Create a JWT that has group claim ala `APIRead`
4) Write another POST test, it should not work due to the read only group claim

I'll be able to look more into this again in a few weeks, so I'll report back if I get any solution that works.

**Comment by JonasKs** [comment]
Starting to work on this on Monday, as I won't be able to reach the ADFS server from my build environment very soon.   
Please let me know if you've made up any thoughts on a solution for this :-)

**Comment by jobec** [comment]
I'd say: an external, separate package, not tied to this one. With config settings allowing to tune how it behaves.

Not embedding it means others will also be able to use it for other things. And on top of that, the focus will then be to mock ADFS. Not specifically craft responses for Django-auth-ADFS.

But of course, embedded in the test suite is also a welcome addition. But it won't be as reusable.

**Comment by JonasKs** [comment]
Alright. I'll have to see if I can justify the scope in work hours, but I'll investigate it. Thanks!

I'll close this ticket for now. :-)

**Comment by srinathganesh1** [comment]
Did you find anything? (for people without constant ADFS access)

I am looking for an alternative by finding out whether LDAP can act as an proxy https://stackoverflow.com/questions/60400856/openldap-to-proxy-for-ad-fs
