### ISSUE TITLE
Next PyPI Release Timeline

### ISSUE THREAD

**Issue by arelcedar** [jobec/django-auth-adfs#79]
We're using `django-auth-adfs` in our project, and it looks like the latest version on github doesn't match the latest version on PyPI (1.2). The `SETTINGS_CLASS` configuration option in master would be very useful to us, so we were wondering if there was any plan to push the latest code to PyPI?

**Comment by junctionapps** [comment]
You may know this already, but you can pip install directly from github in these cases when the official packages aren't yet ready.
https://pip.pypa.io/en/latest/reference/pip_install/#git
https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

**Comment by jobec** [comment]
Don't panic, the project isn't dead yet :)

I'm just not very active during summer time. There are also some changes in my personal life because of which I temporarily have less time to work on this.

I'll see what I can do to release a new version in the next couple of weeks/month.

**Comment by jobec** [comment]
@arelcedar the next release is almost there.

Would you mind removing your forked package from pypi after the next release?
https://pypi.org/project/cedar-adfs-forked/
My name is all over the place in that package and it links back to this repo, but I've got nothing to do with that package. When I first noticed it, I thought it was a potentially malware package.

**Comment by jobec** [comment]
Released 1.3.0

**Comment by jobec** [comment]
@arelcedar

A little reminder to remove your cedar-adfs-forked project from PyPI.

**Comment by JonasKs** [comment]
Seems like it's still there @arelcedar .

Also @jobec , any plans to release a new version now? There is a few bugfixes in it.
