### ISSUE TITLE
Specify Redirect URI (HTTPS)

### ISSUE THREAD

**Issue by tedwards1996** [jobec/django-auth-adfs#82]
I am going through a security hardening process right now, which includes setting up HTTPS. 

All the certificates are in place. When the client manager / active directory side of things is changed from a redirect of HTTP to HTTPS, an error gets thrown. 

I believe this is because Django ADFS automatically assumes that the redirect URI is HTTP. So Django sends a redirect of http://web.site.com and the client manager compares that against http**s**//:web.site.com.

These two redirects do not match up, causing no authentication process to occur / an error to be thrown. Is there a way to specify the redirect URI on the django side so that it is compatible with HTTPS protocols? Maybe something needs to be changed in the settings.py side of things?

**Comment by JonasKs** [comment]
Where do you see this error? In ADFS or in Django? If it’s in ADFS your ADFS redirect url is probably misconfigured. 
Can you enable logging (see the docs) and provide them? 

In your `ADFS` config, you do not need to specify protocol. Simply write: 

```py
AUTH_ADFS = {
    ...
    'SERVER': 'adfs.myserver.com',
    ...
}
```

**Comment by jobec** [comment]
The redirect URL is dynamically generated.

If it generates HTTP URIs, then your Django setup is not aware it's running on HTTPS.
See here for some clues on how to configure it properly: https://docs.djangoproject.com/en/2.2/topics/security/#ssl-https

**Comment by jobec** [comment]
@tedwards1996 Did you manage to get it working by modifying Django's config?

**Comment by jobec** [comment]
@tedwards1996 Did you manage to get it working by modifying Django's config?

**Comment by tedwards1996** [comment]
@jobec I was not able to get it working correctly. I could not find the correct Django / Django Auth ADFS settings to have the information be HTTPS instead of HTTP.

I tried **SECURE_SSL_REDIRECT** however that was not cooperating

**Comment by jobec** [comment]
It works differently. `SECURE_PROXY_SSL_HEADER` is the setting you need to look at.

It boils down to setting that setting like this:
```python
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
```
And then, on your webserver/load balancer/... that terminates the HTTPS connections and proxies the connection to django, you inject a header named `X-Forwarded-Proto` with a value of `https`.
Based on that, Django will then start generating HTTPS links, instead of HTTP.

**Comment by jobec** [comment]
@tedwards1996 were you able to get it working by using that `SECURE_PROXY_SSL_HEADER` I mentioned above?

**Comment by jobec** [comment]
Closed due to inactivity

**Comment by anarchistMegaByte** [comment]
Hello, facing similar issue. @jobec It did not work for me can you help ?

**Comment by harshit148** [comment]
@jobec This did not work for me

> It works differently. `SECURE_PROXY_SSL_HEADER` is the setting you need to look at.
> 
> It boils down to setting that setting like this:
> 
> SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
> And then, on your webserver/load balancer/... that terminates the HTTPS connections and proxies the connection to django, you inject a header named `X-Forwarded-Proto` with a value of `https`. Based on that, Django will then start generating HTTPS links, instead of HTTP.

**Comment by tim-schilling** [comment]
@harshit148 If you'd like to report an issue, please open a new issue and include the information to reproduce it, along with what you've tried. In this case, responding to a comment from five years ago isn't likely to lead to a positive result.
