### ISSUE TITLE
Multiple client_id/relying_party_id pairings for the same adfs server

### ISSUE THREAD

**Issue by fgscivittaro** [jobec/django-auth-adfs#83]
I have a Django app that already has ADFS ready to go to and working smoothly for a single CLIENT_ID/RELYING_PARTY_ID pairing:

```
# settings.py

AUTH_ADFS = {
    "SERVER": "adfs.mywebapp.com",

    "CLIENT_ID": "myclient-id-1",
    "RELYING_PARTY_ID": "mywebapp.com",

    # ...

    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
}
```

My app, however, has two URLs (the default one created by AWS Elastic Beanstalk and another more concise one created using AWS's DNS service). I have CLIENT_ID/RELYING_PARTY_ID pairings for each of these, too. I can successfully use ADFS for either one of these individually, but I would like my users to be able to use **both** to reach the ADFS server. Is this possible using Django ADFS?

```
 "CLIENT_ID": "myclient-id-1",
 "RELYING_PARTY_ID": "mywebapp.com"
```

```
 "CLIENT_ID": "myclient-id-2",
 "RELYING_PARTY_ID": "mywebapp.elasticbeanstalk.com"
```

**Comment by jobec** [comment]
No, not at the moment.

You can always add more then 1 redirect URI to your ADFS configuration. That way you can use a single Client ID, but allow redirects to multiple locations.

**Comment by jobec** [comment]
@fgscivittaro have you tried adding an extra redirect URI to your ADFS configuration? If so, did that fix your problem?

**Comment by jobec** [comment]
Closed due to inactivity
