### ISSUE TITLE
Token validation with Graphene (GraphQL)

### ISSUE THREAD

**Issue by AliNjie** [jobec/django-auth-adfs#85]
Hi!
I’m trying to use django_auth_adfs in my Django project, but using GraphQL instead of drf.

I cannot seem to figure out how the process of validating an access token and creating a Django user would fit in to this? Would I have to create my own custom middleware or does django_auth_adfs expose any helper functions to do the validation and user creation part?

Any suggestions on the matter would be highly appreciated!

**Comment by jobec** [comment]
Which package are you talking about? This one: https://github.com/graphql-python/graphene-django ?

**Comment by AliNjie** [comment]
Yes. In combination with [the regular Graphene implementation](https://graphene-python.org/).
I ended up using `AdfsAccessTokenBackend()` to do request authentication, which seems to work fine. I've also implemented a GraphQL middleware to check whether the `request.user.is_authenticated` is `True`, which works fine for now.

I'll let you know if there are any other questions related to this. Thanks!
