### ISSUE TITLE
redirection after logout

### ISSUE THREAD

**Issue by VBobCat** [jobec/django-auth-adfs#89]
Hello! I'm using **django-auth-adfs** with Azure AD for authentication.

I'm sorry if this feature already exists and I'm not aware of that, but it would be nice if there was a setting for us to define an url to which browser should be redirected after logout.

At the moment, it stops in https://login.microsoftonline.com/login.srf?wa=wsignoutcleanup1.0..., but I would like to make it return to my home page.

Thank you very much.

**Comment by jobec** [comment]
It's indeed a feature of OpenID Connect/Azure AD to redirect after logging out by specifying the `post_logout_redirect_uri` parameter when sending a client to the `end_session_endpoint`.

But the thing is, I never got this working on ADFS 4.0 (windows server 2016) nor on Azure AD. The ADFS server didn't do anything with the parameter. ADFS 3.0 on Windows 2012 doesn't support it either way.

I'll see if I can get it working this time.

**Comment by JonasKs** [comment]
Can confirm, we were also never able to do it on 2016. Ended up doing the logout in a hidden iframe on our custom logout site. Iframes has an on load option, so we have a loading bar that spins until the site is done loading.

**Comment by jobec** [comment]
I tried it once more, but still could not find a way to get it working.
Closing this for the time being. If anyone would figure out how to redirect after logout, feel free to reopen.

**Comment by konradko** [comment]
`id_token_hint` query parameter with ADFS token value needs to be included for `post_logout_redirect_uri` to work, see https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/677

Can be done by catching the [post_authenticate signal]( https://github.com/snok/django-auth-adfs/blob/master/django_auth_adfs/backend.py#L112), saving it in user session (cookie) and setting via a tag template tag or saving against user in DB and then overriding `OAuth2LogoutView` to include `id_token_hint` in the URL from `_get_end_session_endpoint`

**Comment by nilutz** [comment]
You can also duck type (in e.g. url.py) to add the `post_logout_redirect_uri` - make sure you have setup the same URI in the azure portal.

```python
from django_auth_adfs.config import provider_config
provider_config.__dict__["_build_end_session_endpoint"] = provider_config.build_end_session_endpoint
provider_config.build_end_session_endpoint = lambda: provider_config._build_end_session_endpoint() + "?post_logout_redirect_uri=https%3A%2F%2Fexample.redirect.com%2F"

urlpatterns += [
    path("oauth2/", include("django_auth_adfs.urls")),
]
```
