### ISSUE TITLE
Disable Automatic User creation?

### ISSUE THREAD

**Issue by dcleveng** [jobec/django-auth-adfs#90]
First off - thank you, this is a simple and easy approach to authentication using ADFS. 

I'd like to avoid creating user accounts automatically and rather create user accounts manually within Django. I do not see a way to disable automatic creation of accounts when the account is absent on the Django side. I realize you can limit this in ADFS, but I'd like to limit it on the application side. Is this possible?

**Comment by jobec** [comment]
No, at this moment it’s not possible.
But it shouldn’t be hard to implement setting for it.

**Comment by jobec** [comment]
A follow up question:

Do you just want to disable users being created? Or also prevent them from being touched in any way?
Because, besides creating a user, it's attributes/groups/flags are also being updates.

https://github.com/jobec/django-auth-adfs/blob/84062cd8eda03dee704fafc4ed1c636d40ef1546/django_auth_adfs/backend.py#L94-L97

**Comment by dcleveng** [comment]
Just prevent users from being created. If they already exist it would be
fine for attributes to be updated, but my goal was to manually manage user
creation within the app rather then have them automatically created.

**Comment by jobec** [comment]
Try the code in the `setting_to_disable_user_creation` branch.
If you set the setting `CREATE_NEW_USERS` to `False`, new users are not created anymore.

**Comment by dcleveng** [comment]
This is perfect. Exactly what I needed. Thank you!

**Comment by jobec** [comment]
And it also works? 👀

**Comment by dcleveng** [comment]
Yes it does. With the testing that I performed it seemed to work great.
