### ISSUE TITLE
Vagrant issue with Demo

### ISSUE THREAD

**Issue by zdrouse** [jobec/django-auth-adfs#97]
Hi there,

Trying to test the demo out to understand how the module all works with ADFS.
Coming across an issue running the demo with Vagrant.  After doing the instructional step for:

`vagrant up web`

I'm noticing the following error:
```bash
web: ++ pip3 install -e /vagrant
web: /vagrant should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
```

That then leads to:
```bash
web: ++ python3 /vagrant/demo/adfs/manage.py makemigrations polls
web: python3: can't open file '/vagrant/demo/adfs/manage.py': [Errno 2] No such file or directory
web: ++ python3 /vagrant/demo/adfs/manage.py migrate
web: ++ python3 /vagrant/demo/formsbased/manage.py makemigrations polls
web: python3: can't open file '/vagrant/demo/formsbased/manage.py': [Errno 2] No such file or directory
web: ++ python3 /vagrant/demo/formsbased/manage.py migrate
web: python3: can't open file '/vagrant/demo/formsbased/manage.py': [Errno 2] No such file or directory
web: ++ echo '10.0.0.2 adfs.example.com'
```

Any guidance for how to make the the loaded VM install django-auth-adfs in editable mode as needed to get passed this?

Thanks!
Looking forward to testing this out.

**Comment by jobec** [comment]
I'm afraid the vagrant file for the demo needs some updating.
The vagrant boxes for windows are also outdated already.

I'm a bit short on time, but I'll see what I can do.

**Comment by jobec** [comment]
Ok, there seems to be an issue with `/vagrant` not being mounted in the debian box I'm using.
Change the box to `debian/buster64` in the vagrant file and it'll work.

**Comment by zdrouse** [comment]
> Ok, there seems to be an issue with `/vagrant` not being mounted in the debian box I'm using.
> Change the box to `debian/buster64` in the vagrant file and it'll work.

Hey @jobec thanks for looking at this so quick.  That worked with the vm box change in the Vagrantfile.  Cheers!

**Comment by zdrouse** [comment]
Sorry to reopen - I'm on the `adfs2016` portion now.  Perhaps something quick again for this one on the 'reload' privisoner?


```bash
==> adfs2016: Successfully added box 'cdaf/WindowsServer' (v2.0.1) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'reload' provisioner could not be found.
* The 'reload' provisioner could not be found.
```

Thanks in advance, I'll continue trying to troubleshoot myself too.

**Comment by buzzware** [comment]
I'm getting the same errors on OSX for adfs2016

**Comment by buzzware** [comment]
This fixed it :
`vagrant plugin install vagrant-reload`

**Comment by buzzware** [comment]
This works https://github.com/jobec/django-auth-adfs/pull/99

**Comment by zdrouse** [comment]
> This works #99

I just started re-visiting my need for this module.  Thanks @buzzware that worked for me to move along with the demo.
